[package]
name = "raxxla"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "_rust_watcher"
crate-type = ["cdylib"]

[dependencies]
noot_core = { path = "../core", features = ["python"]}
pyo3 = "0.28.2"
crossbeam = "0.8.4"
anyhow = "1.0.101"
pythonize = "0.28.0"