#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "When owner opens carrier management"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"description\": \"When owner opens carrier management\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"AllowNotorious\","]
#[doc = "    \"Callsign\","]
#[doc = "    \"CarrierID\","]
#[doc = "    \"Crew\","]
#[doc = "    \"DockingAccess\","]
#[doc = "    \"Finance\","]
#[doc = "    \"FuelLevel\","]
#[doc = "    \"JumpRangeCurr\","]
#[doc = "    \"JumpRangeMax\","]
#[doc = "    \"ModulePacks\","]
#[doc = "    \"Name\","]
#[doc = "    \"PendingDecommission\","]
#[doc = "    \"ShipPacks\","]
#[doc = "    \"SpaceUsage\","]
#[doc = "    \"event\","]
#[doc = "    \"timestamp\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"AllowNotorious\": {"]
#[doc = "      \"title\": \"AllowNotorious\","]
#[doc = "      \"examples\": ["]
#[doc = "        true,"]
#[doc = "        false"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"Callsign\": {"]
#[doc = "      \"title\": \"Callsign\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"A1A-B2B\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"CarrierID\": {"]
#[doc = "      \"title\": \"CarrierID\","]
#[doc = "      \"examples\": ["]
#[doc = "        3705689344,"]
#[doc = "        3707430144,"]
#[doc = "        3705124096"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"CarrierType\": {"]
#[doc = "      \"title\": \"CarrierType\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"FleetCarrier\","]
#[doc = "        \"SquadronCarrier\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Crew\": {"]
#[doc = "      \"title\": \"Crew\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"Activated\","]
#[doc = "          \"CrewRole\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"Activated\": {"]
#[doc = "            \"title\": \"Activated\","]
#[doc = "            \"examples\": ["]
#[doc = "              true,"]
#[doc = "              false"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          },"]
#[doc = "          \"CrewName\": {"]
#[doc = "            \"title\": \"CrewName\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Casey Jimenez\","]
#[doc = "              \"Rufus Jefferson\","]
#[doc = "              \"Abby Stanley\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"CrewRole\": {"]
#[doc = "            \"title\": \"CrewRole\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"BlackMarket\","]
#[doc = "              \"Captain\","]
#[doc = "              \"Refuel\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Enabled\": {"]
#[doc = "            \"title\": \"Enabled\","]
#[doc = "            \"examples\": ["]
#[doc = "              true,"]
#[doc = "              false"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"DockingAccess\": {"]
#[doc = "      \"title\": \"DockingAccess\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"all\","]
#[doc = "        \"friends\","]
#[doc = "        \"squadronfriends\","]
#[doc = "        \"squadron\","]
#[doc = "        \"none\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Finance\": {"]
#[doc = "      \"title\": \"Finance\","]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"AvailableBalance\","]
#[doc = "        \"CarrierBalance\","]
#[doc = "        \"ReserveBalance\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"AvailableBalance\": {"]
#[doc = "          \"title\": \"AvailableBalance\","]
#[doc = "          \"examples\": ["]
#[doc = "            1032181443,"]
#[doc = "            1533671510,"]
#[doc = "            1483671510"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"CarrierBalance\": {"]
#[doc = "          \"title\": \"CarrierBalance\","]
#[doc = "          \"examples\": ["]
#[doc = "            1159941475,"]
#[doc = "            1661431542,"]
#[doc = "            1660931542"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"ReserveBalance\": {"]
#[doc = "          \"title\": \"ReserveBalance\","]
#[doc = "          \"examples\": ["]
#[doc = "            127749688,"]
#[doc = "            0,"]
#[doc = "            200000000"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"ReservePercent\": {"]
#[doc = "          \"title\": \"ReservePercent\","]
#[doc = "          \"examples\": ["]
#[doc = "            11,"]
#[doc = "            8,"]
#[doc = "            9"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"TaxRate\": {"]
#[doc = "          \"title\": \"TaxRate\","]
#[doc = "          \"examples\": ["]
#[doc = "            10,"]
#[doc = "            0,"]
#[doc = "            25"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"TaxRate_outfitting\": {"]
#[doc = "          \"title\": \"TaxRate_outfitting\","]
#[doc = "          \"examples\": ["]
#[doc = "            25,"]
#[doc = "            2"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"TaxRate_pioneersupplies\": {"]
#[doc = "          \"title\": \"TaxRate_pioneersupplies\","]
#[doc = "          \"examples\": ["]
#[doc = "            25,"]
#[doc = "            0,"]
#[doc = "            2"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"TaxRate_rearm\": {"]
#[doc = "          \"title\": \"TaxRate_rearm\","]
#[doc = "          \"examples\": ["]
#[doc = "            25,"]
#[doc = "            0,"]
#[doc = "            2"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"TaxRate_refuel\": {"]
#[doc = "          \"title\": \"TaxRate_refuel\","]
#[doc = "          \"examples\": ["]
#[doc = "            25,"]
#[doc = "            0,"]
#[doc = "            2"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"TaxRate_repair\": {"]
#[doc = "          \"title\": \"TaxRate_repair\","]
#[doc = "          \"examples\": ["]
#[doc = "            25,"]
#[doc = "            0,"]
#[doc = "            2"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"TaxRate_shipyard\": {"]
#[doc = "          \"title\": \"TaxRate_shipyard\","]
#[doc = "          \"examples\": ["]
#[doc = "            25,"]
#[doc = "            0,"]
#[doc = "            2"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"additionalProperties\": false"]
#[doc = "    },"]
#[doc = "    \"FuelLevel\": {"]
#[doc = "      \"title\": \"FuelLevel\","]
#[doc = "      \"examples\": ["]
#[doc = "        609,"]
#[doc = "        564,"]
#[doc = "        519"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"JumpRangeCurr\": {"]
#[doc = "      \"title\": \"JumpRangeCurr\","]
#[doc = "      \"examples\": ["]
#[doc = "        500.0,"]
#[doc = "        464.46109,"]
#[doc = "        426.47171"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"JumpRangeMax\": {"]
#[doc = "      \"title\": \"JumpRangeMax\","]
#[doc = "      \"examples\": ["]
#[doc = "        500.0"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"ModulePacks\": {"]
#[doc = "      \"title\": \"ModulePacks\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"PackTheme\","]
#[doc = "          \"PackTier\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"PackTheme\": {"]
#[doc = "            \"title\": \"PackTheme\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Limpets\","]
#[doc = "              \"Mining Tools\","]
#[doc = "              \"Mining Utilities\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"PackTier\": {"]
#[doc = "            \"title\": \"PackTier\","]
#[doc = "            \"examples\": ["]
#[doc = "              2,"]
#[doc = "              3,"]
#[doc = "              1"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"Name\": {"]
#[doc = "      \"title\": \"Name\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Carrier Friendly Name\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"PendingDecommission\": {"]
#[doc = "      \"title\": \"PendingDecommission\","]
#[doc = "      \"examples\": ["]
#[doc = "        false"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"ShipPacks\": {"]
#[doc = "      \"title\": \"ShipPacks\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"PackTheme\","]
#[doc = "          \"PackTier\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"PackTheme\": {"]
#[doc = "            \"title\": \"PackTheme\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Zorgon Peterson - Cargo\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"PackTier\": {"]
#[doc = "            \"title\": \"PackTier\","]
#[doc = "            \"examples\": ["]
#[doc = "              1"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"SpaceUsage\": {"]
#[doc = "      \"title\": \"SpaceUsage\","]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"Cargo\","]
#[doc = "        \"CargoSpaceReserved\","]
#[doc = "        \"Crew\","]
#[doc = "        \"FreeSpace\","]
#[doc = "        \"ModulePacks\","]
#[doc = "        \"ShipPacks\","]
#[doc = "        \"TotalCapacity\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"Cargo\": {"]
#[doc = "          \"title\": \"Cargo\","]
#[doc = "          \"examples\": ["]
#[doc = "            2770,"]
#[doc = "            2769,"]
#[doc = "            2899"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"CargoSpaceReserved\": {"]
#[doc = "          \"title\": \"CargoSpaceReserved\","]
#[doc = "          \"examples\": ["]
#[doc = "            4,"]
#[doc = "            5,"]
#[doc = "            20"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"Crew\": {"]
#[doc = "          \"title\": \"Crew\","]
#[doc = "          \"examples\": ["]
#[doc = "            6150,"]
#[doc = "            6620,"]
#[doc = "            930"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"FreeSpace\": {"]
#[doc = "          \"title\": \"FreeSpace\","]
#[doc = "          \"examples\": ["]
#[doc = "            9962,"]
#[doc = "            15606,"]
#[doc = "            15605"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"ModulePacks\": {"]
#[doc = "          \"title\": \"ModulePacks\","]
#[doc = "          \"examples\": ["]
#[doc = "            6114,"]
#[doc = "            0,"]
#[doc = "            6204"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"ShipPacks\": {"]
#[doc = "          \"title\": \"ShipPacks\","]
#[doc = "          \"examples\": ["]
#[doc = "            0,"]
#[doc = "            1790"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"TotalCapacity\": {"]
#[doc = "          \"title\": \"TotalCapacity\","]
#[doc = "          \"examples\": ["]
#[doc = "            25000"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"additionalProperties\": false"]
#[doc = "    },"]
#[doc = "    \"event\": {"]
#[doc = "      \"title\": \"event\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"AfmuRepairs\","]
#[doc = "        \"FSDJump\","]
#[doc = "        \"Location\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"timestamp\": {"]
#[doc = "      \"title\": \"timestamp\","]
#[doc = "      \"description\": \"Timestamp in UTC, ISO 8601\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"2022-09-11T22:00:45Z\","]
#[doc = "        \"2022-09-12T08:54:21Z\","]
#[doc = "        \"2022-09-12T08:54:24Z\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"format\": \"date-time\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CarrierStats {
    #[serde(rename = "AllowNotorious")]
    pub allow_notorious: bool,
    #[serde(rename = "Callsign")]
    pub callsign: ::std::string::String,
    #[serde(rename = "CarrierID")]
    pub carrier_id: i64,
    #[serde(
        rename = "CarrierType",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub carrier_type: ::std::option::Option<::std::string::String>,
    #[serde(rename = "Crew")]
    pub crew: ::std::vec::Vec<CrewItem>,
    #[serde(rename = "DockingAccess")]
    pub docking_access: ::std::string::String,
    #[serde(skip_deserializing, default = "CarrierStats::event_value")]
    pub event: String,
    #[serde(rename = "Finance")]
    pub finance: Finance,
    #[serde(rename = "FuelLevel")]
    pub fuel_level: i64,
    #[serde(rename = "JumpRangeCurr")]
    pub jump_range_curr: f64,
    #[serde(rename = "JumpRangeMax")]
    pub jump_range_max: f64,
    #[serde(rename = "ModulePacks")]
    pub module_packs: ::std::vec::Vec<ModulePacksItem>,
    #[serde(rename = "Name")]
    pub name: ::std::string::String,
    #[serde(rename = "PendingDecommission")]
    pub pending_decommission: bool,
    #[serde(rename = "ShipPacks")]
    pub ship_packs: ::std::vec::Vec<ShipPacksItem>,
    #[serde(rename = "SpaceUsage")]
    pub space_usage: SpaceUsage,
    #[doc = "Timestamp in UTC, ISO 8601"]
    pub timestamp: ::chrono::DateTime<::chrono::offset::Utc>,
}
impl ::std::convert::From<&CarrierStats> for CarrierStats {
    fn from(value: &CarrierStats) -> Self {
        value.clone()
    }
}
#[doc = "`CrewItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Activated\","]
#[doc = "    \"CrewRole\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Activated\": {"]
#[doc = "      \"title\": \"Activated\","]
#[doc = "      \"examples\": ["]
#[doc = "        true,"]
#[doc = "        false"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"CrewName\": {"]
#[doc = "      \"title\": \"CrewName\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Casey Jimenez\","]
#[doc = "        \"Rufus Jefferson\","]
#[doc = "        \"Abby Stanley\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"CrewRole\": {"]
#[doc = "      \"title\": \"CrewRole\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"BlackMarket\","]
#[doc = "        \"Captain\","]
#[doc = "        \"Refuel\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Enabled\": {"]
#[doc = "      \"title\": \"Enabled\","]
#[doc = "      \"examples\": ["]
#[doc = "        true,"]
#[doc = "        false"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CrewItem {
    #[serde(rename = "Activated")]
    pub activated: bool,
    #[serde(
        rename = "CrewName",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub crew_name: ::std::option::Option<::std::string::String>,
    #[serde(rename = "CrewRole")]
    pub crew_role: ::std::string::String,
    #[serde(
        rename = "Enabled",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub enabled: ::std::option::Option<bool>,
}
impl ::std::convert::From<&CrewItem> for CrewItem {
    fn from(value: &CrewItem) -> Self {
        value.clone()
    }
}
#[doc = "`Finance`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"Finance\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"AvailableBalance\","]
#[doc = "    \"CarrierBalance\","]
#[doc = "    \"ReserveBalance\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"AvailableBalance\": {"]
#[doc = "      \"title\": \"AvailableBalance\","]
#[doc = "      \"examples\": ["]
#[doc = "        1032181443,"]
#[doc = "        1533671510,"]
#[doc = "        1483671510"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"CarrierBalance\": {"]
#[doc = "      \"title\": \"CarrierBalance\","]
#[doc = "      \"examples\": ["]
#[doc = "        1159941475,"]
#[doc = "        1661431542,"]
#[doc = "        1660931542"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"ReserveBalance\": {"]
#[doc = "      \"title\": \"ReserveBalance\","]
#[doc = "      \"examples\": ["]
#[doc = "        127749688,"]
#[doc = "        0,"]
#[doc = "        200000000"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"ReservePercent\": {"]
#[doc = "      \"title\": \"ReservePercent\","]
#[doc = "      \"examples\": ["]
#[doc = "        11,"]
#[doc = "        8,"]
#[doc = "        9"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"TaxRate\": {"]
#[doc = "      \"title\": \"TaxRate\","]
#[doc = "      \"examples\": ["]
#[doc = "        10,"]
#[doc = "        0,"]
#[doc = "        25"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"TaxRate_outfitting\": {"]
#[doc = "      \"title\": \"TaxRate_outfitting\","]
#[doc = "      \"examples\": ["]
#[doc = "        25,"]
#[doc = "        2"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"TaxRate_pioneersupplies\": {"]
#[doc = "      \"title\": \"TaxRate_pioneersupplies\","]
#[doc = "      \"examples\": ["]
#[doc = "        25,"]
#[doc = "        0,"]
#[doc = "        2"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"TaxRate_rearm\": {"]
#[doc = "      \"title\": \"TaxRate_rearm\","]
#[doc = "      \"examples\": ["]
#[doc = "        25,"]
#[doc = "        0,"]
#[doc = "        2"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"TaxRate_refuel\": {"]
#[doc = "      \"title\": \"TaxRate_refuel\","]
#[doc = "      \"examples\": ["]
#[doc = "        25,"]
#[doc = "        0,"]
#[doc = "        2"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"TaxRate_repair\": {"]
#[doc = "      \"title\": \"TaxRate_repair\","]
#[doc = "      \"examples\": ["]
#[doc = "        25,"]
#[doc = "        0,"]
#[doc = "        2"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"TaxRate_shipyard\": {"]
#[doc = "      \"title\": \"TaxRate_shipyard\","]
#[doc = "      \"examples\": ["]
#[doc = "        25,"]
#[doc = "        0,"]
#[doc = "        2"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct Finance {
    #[serde(rename = "AvailableBalance")]
    pub available_balance: i64,
    #[serde(rename = "CarrierBalance")]
    pub carrier_balance: i64,
    #[serde(rename = "ReserveBalance")]
    pub reserve_balance: i64,
    #[serde(
        rename = "ReservePercent",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub reserve_percent: ::std::option::Option<i64>,
    #[serde(
        rename = "TaxRate",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub tax_rate: ::std::option::Option<i64>,
    #[serde(
        rename = "TaxRate_outfitting",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub tax_rate_outfitting: ::std::option::Option<i64>,
    #[serde(
        rename = "TaxRate_pioneersupplies",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub tax_rate_pioneersupplies: ::std::option::Option<i64>,
    #[serde(
        rename = "TaxRate_rearm",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub tax_rate_rearm: ::std::option::Option<i64>,
    #[serde(
        rename = "TaxRate_refuel",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub tax_rate_refuel: ::std::option::Option<i64>,
    #[serde(
        rename = "TaxRate_repair",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub tax_rate_repair: ::std::option::Option<i64>,
    #[serde(
        rename = "TaxRate_shipyard",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub tax_rate_shipyard: ::std::option::Option<i64>,
}
impl ::std::convert::From<&Finance> for Finance {
    fn from(value: &Finance) -> Self {
        value.clone()
    }
}
#[doc = "`ModulePacksItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"PackTheme\","]
#[doc = "    \"PackTier\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"PackTheme\": {"]
#[doc = "      \"title\": \"PackTheme\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Limpets\","]
#[doc = "        \"Mining Tools\","]
#[doc = "        \"Mining Utilities\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"PackTier\": {"]
#[doc = "      \"title\": \"PackTier\","]
#[doc = "      \"examples\": ["]
#[doc = "        2,"]
#[doc = "        3,"]
#[doc = "        1"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ModulePacksItem {
    #[serde(rename = "PackTheme")]
    pub pack_theme: ::std::string::String,
    #[serde(rename = "PackTier")]
    pub pack_tier: i64,
}
impl ::std::convert::From<&ModulePacksItem> for ModulePacksItem {
    fn from(value: &ModulePacksItem) -> Self {
        value.clone()
    }
}
#[doc = "`ShipPacksItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"PackTheme\","]
#[doc = "    \"PackTier\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"PackTheme\": {"]
#[doc = "      \"title\": \"PackTheme\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Zorgon Peterson - Cargo\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"PackTier\": {"]
#[doc = "      \"title\": \"PackTier\","]
#[doc = "      \"examples\": ["]
#[doc = "        1"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ShipPacksItem {
    #[serde(rename = "PackTheme")]
    pub pack_theme: ::std::string::String,
    #[serde(rename = "PackTier")]
    pub pack_tier: i64,
}
impl ::std::convert::From<&ShipPacksItem> for ShipPacksItem {
    fn from(value: &ShipPacksItem) -> Self {
        value.clone()
    }
}
#[doc = "`SpaceUsage`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"SpaceUsage\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Cargo\","]
#[doc = "    \"CargoSpaceReserved\","]
#[doc = "    \"Crew\","]
#[doc = "    \"FreeSpace\","]
#[doc = "    \"ModulePacks\","]
#[doc = "    \"ShipPacks\","]
#[doc = "    \"TotalCapacity\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Cargo\": {"]
#[doc = "      \"title\": \"Cargo\","]
#[doc = "      \"examples\": ["]
#[doc = "        2770,"]
#[doc = "        2769,"]
#[doc = "        2899"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"CargoSpaceReserved\": {"]
#[doc = "      \"title\": \"CargoSpaceReserved\","]
#[doc = "      \"examples\": ["]
#[doc = "        4,"]
#[doc = "        5,"]
#[doc = "        20"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Crew\": {"]
#[doc = "      \"title\": \"Crew\","]
#[doc = "      \"examples\": ["]
#[doc = "        6150,"]
#[doc = "        6620,"]
#[doc = "        930"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"FreeSpace\": {"]
#[doc = "      \"title\": \"FreeSpace\","]
#[doc = "      \"examples\": ["]
#[doc = "        9962,"]
#[doc = "        15606,"]
#[doc = "        15605"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"ModulePacks\": {"]
#[doc = "      \"title\": \"ModulePacks\","]
#[doc = "      \"examples\": ["]
#[doc = "        6114,"]
#[doc = "        0,"]
#[doc = "        6204"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"ShipPacks\": {"]
#[doc = "      \"title\": \"ShipPacks\","]
#[doc = "      \"examples\": ["]
#[doc = "        0,"]
#[doc = "        1790"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"TotalCapacity\": {"]
#[doc = "      \"title\": \"TotalCapacity\","]
#[doc = "      \"examples\": ["]
#[doc = "        25000"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct SpaceUsage {
    #[serde(rename = "Cargo")]
    pub cargo: i64,
    #[serde(rename = "CargoSpaceReserved")]
    pub cargo_space_reserved: i64,
    #[serde(rename = "Crew")]
    pub crew: i64,
    #[serde(rename = "FreeSpace")]
    pub free_space: i64,
    #[serde(rename = "ModulePacks")]
    pub module_packs: i64,
    #[serde(rename = "ShipPacks")]
    pub ship_packs: i64,
    #[serde(rename = "TotalCapacity")]
    pub total_capacity: i64,
}
impl ::std::convert::From<&SpaceUsage> for SpaceUsage {
    fn from(value: &SpaceUsage) -> Self {
        value.clone()
    }
}

impl CarrierStats {
    pub fn event_value() -> ::std::string::String {
        "CarrierStats".to_string()
    }
}
