#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "When written: when the game retrieves info on community goals from the server, and the data has changed since last time. This event contains the current status of all community goals the player is currently subscribed to."]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"description\": \"When written: when the game retrieves info on community goals from the server, and the data has changed since last time. This event contains the current status of all community goals the player is currently subscribed to.\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"CurrentGoals\","]
#[doc = "    \"event\","]
#[doc = "    \"timestamp\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"CurrentGoals\": {"]
#[doc = "      \"title\": \"CurrentGoals\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"CGID\","]
#[doc = "          \"CurrentTotal\","]
#[doc = "          \"Expiry\","]
#[doc = "          \"IsComplete\","]
#[doc = "          \"MarketName\","]
#[doc = "          \"NumContributors\","]
#[doc = "          \"PlayerContribution\","]
#[doc = "          \"PlayerPercentileBand\","]
#[doc = "          \"SystemName\","]
#[doc = "          \"Title\","]
#[doc = "          \"TopTier\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"Bonus\": {"]
#[doc = "            \"title\": \"Bonus\","]
#[doc = "            \"description\": \"If the community goal has reached the first success\","]
#[doc = "            \"examples\": ["]
#[doc = "              2400000,"]
#[doc = "              8000000,"]
#[doc = "              1000000"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"CGID\": {"]
#[doc = "            \"title\": \"CGID\","]
#[doc = "            \"description\": \"A unique ID number for the CG\","]
#[doc = "            \"examples\": ["]
#[doc = "              754,"]
#[doc = "              758,"]
#[doc = "              690"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"CurrentTotal\": {"]
#[doc = "            \"title\": \"CurrentTotal\","]
#[doc = "            \"examples\": ["]
#[doc = "              979809560710,"]
#[doc = "              979819883710,"]
#[doc = "              981475941910"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"Expiry\": {"]
#[doc = "            \"title\": \"Expiry\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"2022-10-13T07:00:00Z\","]
#[doc = "              \"2022-11-10T08:00:00Z\","]
#[doc = "              \"2021-11-11T06:00:00Z\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\","]
#[doc = "            \"format\": \"date-time\""]
#[doc = "          },"]
#[doc = "          \"IsComplete\": {"]
#[doc = "            \"title\": \"IsComplete\","]
#[doc = "            \"examples\": ["]
#[doc = "              false,"]
#[doc = "              true"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          },"]
#[doc = "          \"MarketName\": {"]
#[doc = "            \"title\": \"MarketName\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Kumiho Sky\","]
#[doc = "              \"MacLean City\","]
#[doc = "              \"Macdonald Settlement\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"NumContributors\": {"]
#[doc = "            \"title\": \"NumContributors\","]
#[doc = "            \"examples\": ["]
#[doc = "              3897,"]
#[doc = "              3900,"]
#[doc = "              3903"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"PlayerContribution\": {"]
#[doc = "            \"title\": \"PlayerContribution\","]
#[doc = "            \"examples\": ["]
#[doc = "              0,"]
#[doc = "              8180000,"]
#[doc = "              9180000"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"PlayerInTopRank\": {"]
#[doc = "            \"title\": \"PlayerInTopRank\","]
#[doc = "            \"description\": \"If the community goal is constructed with a fixed-size top rank (ie max reward for top 10 players)\","]
#[doc = "            \"examples\": ["]
#[doc = "              false,"]
#[doc = "              true"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          },"]
#[doc = "          \"PlayerPercentileBand\": {"]
#[doc = "            \"title\": \"PlayerPercentileBand\","]
#[doc = "            \"examples\": ["]
#[doc = "              100,"]
#[doc = "              75,"]
#[doc = "              50"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"SystemName\": {"]
#[doc = "            \"title\": \"SystemName\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Andecavi\","]
#[doc = "              \"Wandrama\","]
#[doc = "              \"Alcor\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"TierReached\": {"]
#[doc = "            \"title\": \"TierReached\","]
#[doc = "            \"description\": \"If the community goal has reached the first success\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Tier 7\","]
#[doc = "              \"Tier 2\","]
#[doc = "              \"Tier 3\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Title\": {"]
#[doc = "            \"title\": \"Title\","]
#[doc = "            \"description\": \"A description for the CG\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Operation Tyndareus Reacts to Thargoid Fleet\","]
#[doc = "              \"Disrupt Azimuth's Resource Campaign\","]
#[doc = "              \"The Colonia Bridge Project 2nd Phase - Alcor\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"TopRankSize\": {"]
#[doc = "            \"title\": \"TopRankSize\","]
#[doc = "            \"description\": \"If the community goal is constructed with a fixed-size top rank (ie max reward for top 10 players)\","]
#[doc = "            \"examples\": ["]
#[doc = "              10"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"TopTier\": {"]
#[doc = "            \"title\": \"TopTier\","]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"required\": ["]
#[doc = "              \"Bonus\","]
#[doc = "              \"Name\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"Bonus\": {"]
#[doc = "                \"title\": \"Bonus\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              },"]
#[doc = "              \"Name\": {"]
#[doc = "                \"title\": \"Name\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"Tier 8\","]
#[doc = "                  \"Tier 6\","]
#[doc = "                  \"Tier 5\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              }"]
#[doc = "            },"]
#[doc = "            \"additionalProperties\": false"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"event\": {"]
#[doc = "      \"title\": \"event\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"AfmuRepairs\","]
#[doc = "        \"FSDJump\","]
#[doc = "        \"Location\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"timestamp\": {"]
#[doc = "      \"title\": \"timestamp\","]
#[doc = "      \"description\": \"Timestamp in UTC, ISO 8601\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"2022-09-11T22:00:45Z\","]
#[doc = "        \"2022-09-12T08:54:21Z\","]
#[doc = "        \"2022-09-12T08:54:24Z\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"format\": \"date-time\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CommunityGoal {
    #[serde(rename = "CurrentGoals")]
    pub current_goals: ::std::vec::Vec<CurrentGoalsItem>,
    #[serde(skip_deserializing, default = "CommunityGoal::event_value")]
    pub event: String,
    #[doc = "Timestamp in UTC, ISO 8601"]
    pub timestamp: ::chrono::DateTime<::chrono::offset::Utc>,
}
impl ::std::convert::From<&CommunityGoal> for CommunityGoal {
    fn from(value: &CommunityGoal) -> Self {
        value.clone()
    }
}
#[doc = "`CurrentGoalsItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"CGID\","]
#[doc = "    \"CurrentTotal\","]
#[doc = "    \"Expiry\","]
#[doc = "    \"IsComplete\","]
#[doc = "    \"MarketName\","]
#[doc = "    \"NumContributors\","]
#[doc = "    \"PlayerContribution\","]
#[doc = "    \"PlayerPercentileBand\","]
#[doc = "    \"SystemName\","]
#[doc = "    \"Title\","]
#[doc = "    \"TopTier\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Bonus\": {"]
#[doc = "      \"title\": \"Bonus\","]
#[doc = "      \"description\": \"If the community goal has reached the first success\","]
#[doc = "      \"examples\": ["]
#[doc = "        2400000,"]
#[doc = "        8000000,"]
#[doc = "        1000000"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"CGID\": {"]
#[doc = "      \"title\": \"CGID\","]
#[doc = "      \"description\": \"A unique ID number for the CG\","]
#[doc = "      \"examples\": ["]
#[doc = "        754,"]
#[doc = "        758,"]
#[doc = "        690"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"CurrentTotal\": {"]
#[doc = "      \"title\": \"CurrentTotal\","]
#[doc = "      \"examples\": ["]
#[doc = "        979809560710,"]
#[doc = "        979819883710,"]
#[doc = "        981475941910"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Expiry\": {"]
#[doc = "      \"title\": \"Expiry\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"2022-10-13T07:00:00Z\","]
#[doc = "        \"2022-11-10T08:00:00Z\","]
#[doc = "        \"2021-11-11T06:00:00Z\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"format\": \"date-time\""]
#[doc = "    },"]
#[doc = "    \"IsComplete\": {"]
#[doc = "      \"title\": \"IsComplete\","]
#[doc = "      \"examples\": ["]
#[doc = "        false,"]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"MarketName\": {"]
#[doc = "      \"title\": \"MarketName\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Kumiho Sky\","]
#[doc = "        \"MacLean City\","]
#[doc = "        \"Macdonald Settlement\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"NumContributors\": {"]
#[doc = "      \"title\": \"NumContributors\","]
#[doc = "      \"examples\": ["]
#[doc = "        3897,"]
#[doc = "        3900,"]
#[doc = "        3903"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"PlayerContribution\": {"]
#[doc = "      \"title\": \"PlayerContribution\","]
#[doc = "      \"examples\": ["]
#[doc = "        0,"]
#[doc = "        8180000,"]
#[doc = "        9180000"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"PlayerInTopRank\": {"]
#[doc = "      \"title\": \"PlayerInTopRank\","]
#[doc = "      \"description\": \"If the community goal is constructed with a fixed-size top rank (ie max reward for top 10 players)\","]
#[doc = "      \"examples\": ["]
#[doc = "        false,"]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"PlayerPercentileBand\": {"]
#[doc = "      \"title\": \"PlayerPercentileBand\","]
#[doc = "      \"examples\": ["]
#[doc = "        100,"]
#[doc = "        75,"]
#[doc = "        50"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"SystemName\": {"]
#[doc = "      \"title\": \"SystemName\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Andecavi\","]
#[doc = "        \"Wandrama\","]
#[doc = "        \"Alcor\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"TierReached\": {"]
#[doc = "      \"title\": \"TierReached\","]
#[doc = "      \"description\": \"If the community goal has reached the first success\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Tier 7\","]
#[doc = "        \"Tier 2\","]
#[doc = "        \"Tier 3\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Title\": {"]
#[doc = "      \"title\": \"Title\","]
#[doc = "      \"description\": \"A description for the CG\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Operation Tyndareus Reacts to Thargoid Fleet\","]
#[doc = "        \"Disrupt Azimuth's Resource Campaign\","]
#[doc = "        \"The Colonia Bridge Project 2nd Phase - Alcor\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"TopRankSize\": {"]
#[doc = "      \"title\": \"TopRankSize\","]
#[doc = "      \"description\": \"If the community goal is constructed with a fixed-size top rank (ie max reward for top 10 players)\","]
#[doc = "      \"examples\": ["]
#[doc = "        10"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"TopTier\": {"]
#[doc = "      \"title\": \"TopTier\","]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"Bonus\","]
#[doc = "        \"Name\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"Bonus\": {"]
#[doc = "          \"title\": \"Bonus\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"Name\": {"]
#[doc = "          \"title\": \"Name\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"Tier 8\","]
#[doc = "            \"Tier 6\","]
#[doc = "            \"Tier 5\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"additionalProperties\": false"]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CurrentGoalsItem {
    #[doc = "If the community goal has reached the first success"]
    #[serde(
        rename = "Bonus",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub bonus: ::std::option::Option<i64>,
    #[doc = "A unique ID number for the CG"]
    #[serde(rename = "CGID")]
    pub cgid: i64,
    #[serde(rename = "CurrentTotal")]
    pub current_total: i64,
    #[serde(rename = "Expiry")]
    pub expiry: ::chrono::DateTime<::chrono::offset::Utc>,
    #[serde(rename = "IsComplete")]
    pub is_complete: bool,
    #[serde(rename = "MarketName")]
    pub market_name: ::std::string::String,
    #[serde(rename = "NumContributors")]
    pub num_contributors: i64,
    #[serde(rename = "PlayerContribution")]
    pub player_contribution: i64,
    #[doc = "If the community goal is constructed with a fixed-size top rank (ie max reward for top 10 players)"]
    #[serde(
        rename = "PlayerInTopRank",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub player_in_top_rank: ::std::option::Option<bool>,
    #[serde(rename = "PlayerPercentileBand")]
    pub player_percentile_band: i64,
    #[serde(rename = "SystemName")]
    pub system_name: ::std::string::String,
    #[doc = "If the community goal has reached the first success"]
    #[serde(
        rename = "TierReached",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub tier_reached: ::std::option::Option<::std::string::String>,
    #[doc = "A description for the CG"]
    #[serde(rename = "Title")]
    pub title: ::std::string::String,
    #[doc = "If the community goal is constructed with a fixed-size top rank (ie max reward for top 10 players)"]
    #[serde(
        rename = "TopRankSize",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub top_rank_size: ::std::option::Option<i64>,
    #[serde(rename = "TopTier")]
    pub top_tier: TopTier,
}
impl ::std::convert::From<&CurrentGoalsItem> for CurrentGoalsItem {
    fn from(value: &CurrentGoalsItem) -> Self {
        value.clone()
    }
}
#[doc = "`TopTier`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"TopTier\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Bonus\","]
#[doc = "    \"Name\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Bonus\": {"]
#[doc = "      \"title\": \"Bonus\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Name\": {"]
#[doc = "      \"title\": \"Name\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Tier 8\","]
#[doc = "        \"Tier 6\","]
#[doc = "        \"Tier 5\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct TopTier {
    #[serde(rename = "Bonus")]
    pub bonus: ::std::string::String,
    #[serde(rename = "Name")]
    pub name: ::std::string::String,
}
impl ::std::convert::From<&TopTier> for TopTier {
    fn from(value: &TopTier) -> Self {
        value.clone()
    }
}

impl CommunityGoal {
    pub fn event_value() -> ::std::string::String {
        "CommunityGoal".to_string()
    }
}
