#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "This event is logged when the player creates a new suit loadout"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"description\": \"This event is logged when the player creates a new suit loadout\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"LoadoutID\","]
#[doc = "    \"LoadoutName\","]
#[doc = "    \"Modules\","]
#[doc = "    \"SuitID\","]
#[doc = "    \"SuitMods\","]
#[doc = "    \"SuitName\","]
#[doc = "    \"event\","]
#[doc = "    \"timestamp\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"LoadoutID\": {"]
#[doc = "      \"title\": \"LoadoutID\","]
#[doc = "      \"examples\": ["]
#[doc = "        4293000016,"]
#[doc = "        4293000018,"]
#[doc = "        4293000019"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"LoadoutName\": {"]
#[doc = "      \"title\": \"LoadoutName\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Artemis extra power\","]
#[doc = "        \"JA TEST\","]
#[doc = "        \"flight suit\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Modules\": {"]
#[doc = "      \"title\": \"Modules\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"Class\","]
#[doc = "          \"ModuleName\","]
#[doc = "          \"SlotName\","]
#[doc = "          \"SuitModuleID\","]
#[doc = "          \"WeaponMods\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"Class\": {"]
#[doc = "            \"title\": \"Class\","]
#[doc = "            \"examples\": ["]
#[doc = "              3,"]
#[doc = "              1,"]
#[doc = "              2"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"ModuleName\": {"]
#[doc = "            \"title\": \"ModuleName\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"wpn_m_assaultrifle_laser_fauto\","]
#[doc = "              \"wpn_m_submachinegun_kinetic_fauto\","]
#[doc = "              \"wpn_m_sniper_plasma_charged\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"ModuleName_Localised\": {"]
#[doc = "            \"title\": \"ModuleName_Localised\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"TK Aphelion\","]
#[doc = "              \"Karma C-44\","]
#[doc = "              \"Manticore Executioner\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"SlotName\": {"]
#[doc = "            \"title\": \"SlotName\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"PrimaryWeapon1\","]
#[doc = "              \"PrimaryWeapon2\","]
#[doc = "              \"SecondaryWeapon\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"SuitModuleID\": {"]
#[doc = "            \"title\": \"SuitModuleID\","]
#[doc = "            \"examples\": ["]
#[doc = "              1722576686732033,"]
#[doc = "              1700362936206349,"]
#[doc = "              1700314434564508"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"WeaponMods\": {"]
#[doc = "            \"title\": \"WeaponMods\","]
#[doc = "            \"default\": null,"]
#[doc = "            \"type\": \"array\","]
#[doc = "            \"items\": {"]
#[doc = "              \"examples\": ["]
#[doc = "                \"weapon_accuracy\","]
#[doc = "                \"weapon_suppression_unpressurised\","]
#[doc = "                \"weapon_handling\""]
#[doc = "              ],"]
#[doc = "              \"type\": \"string\""]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"SuitID\": {"]
#[doc = "      \"title\": \"SuitID\","]
#[doc = "      \"examples\": ["]
#[doc = "        1722459265319146,"]
#[doc = "        1722471630829214,"]
#[doc = "        1700215335054978"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"SuitMods\": {"]
#[doc = "      \"title\": \"SuitMods\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"examples\": ["]
#[doc = "          \"suit_increasedbatterycapacity\","]
#[doc = "          \"suit_improvedjumpassist\","]
#[doc = "          \"suit_improvedradar\""]
#[doc = "        ],"]
#[doc = "        \"type\": \"string\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"SuitName\": {"]
#[doc = "      \"title\": \"SuitName\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"explorationsuit_class2\","]
#[doc = "        \"explorationsuit_class3\","]
#[doc = "        \"flightsuit\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"SuitName_Localised\": {"]
#[doc = "      \"title\": \"SuitName_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"$ExplorationSuit_Class1_Name;\","]
#[doc = "        \"Flight Suit\","]
#[doc = "        \"$TacticalSuit_Class1_Name;\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"event\": {"]
#[doc = "      \"title\": \"event\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"AfmuRepairs\","]
#[doc = "        \"FSDJump\","]
#[doc = "        \"Location\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"timestamp\": {"]
#[doc = "      \"title\": \"timestamp\","]
#[doc = "      \"description\": \"Timestamp in UTC, ISO 8601\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"2022-09-11T22:00:45Z\","]
#[doc = "        \"2022-09-12T08:54:21Z\","]
#[doc = "        \"2022-09-12T08:54:24Z\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"format\": \"date-time\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CreateSuitLoadout {
    #[serde(skip_deserializing, default = "CreateSuitLoadout::event_value")]
    pub event: String,
    #[serde(rename = "LoadoutID")]
    pub loadout_id: i64,
    #[serde(rename = "LoadoutName")]
    pub loadout_name: ::std::string::String,
    #[serde(rename = "Modules")]
    pub modules: ::std::vec::Vec<ModulesItem>,
    #[serde(rename = "SuitID")]
    pub suit_id: i64,
    #[serde(rename = "SuitMods")]
    pub suit_mods: ::std::vec::Vec<::std::string::String>,
    #[serde(rename = "SuitName")]
    pub suit_name: ::std::string::String,
    #[serde(
        rename = "SuitName_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub suit_name_localised: ::std::option::Option<::std::string::String>,
    #[doc = "Timestamp in UTC, ISO 8601"]
    pub timestamp: ::chrono::DateTime<::chrono::offset::Utc>,
}
impl ::std::convert::From<&CreateSuitLoadout> for CreateSuitLoadout {
    fn from(value: &CreateSuitLoadout) -> Self {
        value.clone()
    }
}
#[doc = "`ModulesItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Class\","]
#[doc = "    \"ModuleName\","]
#[doc = "    \"SlotName\","]
#[doc = "    \"SuitModuleID\","]
#[doc = "    \"WeaponMods\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Class\": {"]
#[doc = "      \"title\": \"Class\","]
#[doc = "      \"examples\": ["]
#[doc = "        3,"]
#[doc = "        1,"]
#[doc = "        2"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"ModuleName\": {"]
#[doc = "      \"title\": \"ModuleName\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"wpn_m_assaultrifle_laser_fauto\","]
#[doc = "        \"wpn_m_submachinegun_kinetic_fauto\","]
#[doc = "        \"wpn_m_sniper_plasma_charged\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"ModuleName_Localised\": {"]
#[doc = "      \"title\": \"ModuleName_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"TK Aphelion\","]
#[doc = "        \"Karma C-44\","]
#[doc = "        \"Manticore Executioner\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"SlotName\": {"]
#[doc = "      \"title\": \"SlotName\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"PrimaryWeapon1\","]
#[doc = "        \"PrimaryWeapon2\","]
#[doc = "        \"SecondaryWeapon\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"SuitModuleID\": {"]
#[doc = "      \"title\": \"SuitModuleID\","]
#[doc = "      \"examples\": ["]
#[doc = "        1722576686732033,"]
#[doc = "        1700362936206349,"]
#[doc = "        1700314434564508"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"WeaponMods\": {"]
#[doc = "      \"title\": \"WeaponMods\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"examples\": ["]
#[doc = "          \"weapon_accuracy\","]
#[doc = "          \"weapon_suppression_unpressurised\","]
#[doc = "          \"weapon_handling\""]
#[doc = "        ],"]
#[doc = "        \"type\": \"string\""]
#[doc = "      }"]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ModulesItem {
    #[serde(rename = "Class")]
    pub class: i64,
    #[serde(rename = "ModuleName")]
    pub module_name: ::std::string::String,
    #[serde(
        rename = "ModuleName_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub module_name_localised: ::std::option::Option<::std::string::String>,
    #[serde(rename = "SlotName")]
    pub slot_name: ::std::string::String,
    #[serde(rename = "SuitModuleID")]
    pub suit_module_id: i64,
    #[serde(rename = "WeaponMods")]
    pub weapon_mods: ::std::vec::Vec<::std::string::String>,
}
impl ::std::convert::From<&ModulesItem> for ModulesItem {
    fn from(value: &ModulesItem) -> Self {
        value.clone()
    }
}

impl CreateSuitLoadout {
    pub fn event_value() -> ::std::string::String {
        "CreateSuitLoadout".to_string()
    }
}
