#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "`ActiveStatesItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"State\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"State\": {"]
#[doc = "      \"title\": \"State\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Boom\","]
#[doc = "        \"Investment\","]
#[doc = "        \"Expansion\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ActiveStatesItem {
    #[serde(rename = "State")]
    pub state: ::std::string::String,
}
impl ::std::convert::From<&ActiveStatesItem> for ActiveStatesItem {
    fn from(value: &ActiveStatesItem) -> Self {
        value.clone()
    }
}
#[doc = "`ConflictsItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Faction1\","]
#[doc = "    \"Faction2\","]
#[doc = "    \"Status\","]
#[doc = "    \"WarType\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Faction1\": {"]
#[doc = "      \"title\": \"Faction1\","]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"Name\","]
#[doc = "        \"Stake\","]
#[doc = "        \"WonDays\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"Name\": {"]
#[doc = "          \"title\": \"Name\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"United HIP 20485 Future\","]
#[doc = "            \"Gucumadhyas Incorporated\","]
#[doc = "            \"Alliance of Wadjang\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"Stake\": {"]
#[doc = "          \"title\": \"Stake\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"SAAvedra Depot\","]
#[doc = "            \"Sagan Landing\","]
#[doc = "            \"$EXT_PANEL_ColonisationShip;\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"Stake_Localised\": {"]
#[doc = "          \"title\": \"Stake_Localised\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"System Colonisation Ship\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"WonDays\": {"]
#[doc = "          \"title\": \"WonDays\","]
#[doc = "          \"examples\": ["]
#[doc = "            0,"]
#[doc = "            1,"]
#[doc = "            2"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"additionalProperties\": false"]
#[doc = "    },"]
#[doc = "    \"Faction2\": {"]
#[doc = "      \"title\": \"Faction2\","]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"Name\","]
#[doc = "        \"Stake\","]
#[doc = "        \"WonDays\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"Name\": {"]
#[doc = "          \"title\": \"Name\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"HIP 20485 Corp.\","]
#[doc = "            \"Bureau of Gucumadhyas Liberty Party\","]
#[doc = "            \"Asooraja Netcoms Inc\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"Stake\": {"]
#[doc = "          \"title\": \"Stake\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"SAAvedra Depot\","]
#[doc = "            \"Sagan Landing\","]
#[doc = "            \"$EXT_PANEL_ColonisationShip;\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"Stake_Localised\": {"]
#[doc = "          \"title\": \"Stake_Localised\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"System Colonisation Ship\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"WonDays\": {"]
#[doc = "          \"title\": \"WonDays\","]
#[doc = "          \"examples\": ["]
#[doc = "            0,"]
#[doc = "            4,"]
#[doc = "            1"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"additionalProperties\": false"]
#[doc = "    },"]
#[doc = "    \"Status\": {"]
#[doc = "      \"title\": \"Status\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"active\","]
#[doc = "        \"pending\","]
#[doc = "        \"\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"WarType\": {"]
#[doc = "      \"title\": \"WarType\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"civilwar\","]
#[doc = "        \"war\","]
#[doc = "        \"election\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ConflictsItem {
    #[serde(rename = "Faction1")]
    pub faction1: Faction1,
    #[serde(rename = "Faction2")]
    pub faction2: Faction2,
    #[serde(rename = "Status")]
    pub status: ::std::string::String,
    #[serde(rename = "WarType")]
    pub war_type: ::std::string::String,
}
impl ::std::convert::From<&ConflictsItem> for ConflictsItem {
    fn from(value: &ConflictsItem) -> Self {
        value.clone()
    }
}
#[doc = "`Faction1`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"Faction1\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Name\","]
#[doc = "    \"Stake\","]
#[doc = "    \"WonDays\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Name\": {"]
#[doc = "      \"title\": \"Name\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"United HIP 20485 Future\","]
#[doc = "        \"Gucumadhyas Incorporated\","]
#[doc = "        \"Alliance of Wadjang\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Stake\": {"]
#[doc = "      \"title\": \"Stake\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"SAAvedra Depot\","]
#[doc = "        \"Sagan Landing\","]
#[doc = "        \"$EXT_PANEL_ColonisationShip;\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Stake_Localised\": {"]
#[doc = "      \"title\": \"Stake_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"System Colonisation Ship\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"WonDays\": {"]
#[doc = "      \"title\": \"WonDays\","]
#[doc = "      \"examples\": ["]
#[doc = "        0,"]
#[doc = "        1,"]
#[doc = "        2"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct Faction1 {
    #[serde(rename = "Name")]
    pub name: ::std::string::String,
    #[serde(rename = "Stake")]
    pub stake: ::std::string::String,
    #[serde(
        rename = "Stake_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub stake_localised: ::std::option::Option<::std::string::String>,
    #[serde(rename = "WonDays")]
    pub won_days: i64,
}
impl ::std::convert::From<&Faction1> for Faction1 {
    fn from(value: &Faction1) -> Self {
        value.clone()
    }
}
#[doc = "`Faction2`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"Faction2\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Name\","]
#[doc = "    \"Stake\","]
#[doc = "    \"WonDays\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Name\": {"]
#[doc = "      \"title\": \"Name\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"HIP 20485 Corp.\","]
#[doc = "        \"Bureau of Gucumadhyas Liberty Party\","]
#[doc = "        \"Asooraja Netcoms Inc\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Stake\": {"]
#[doc = "      \"title\": \"Stake\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"SAAvedra Depot\","]
#[doc = "        \"Sagan Landing\","]
#[doc = "        \"$EXT_PANEL_ColonisationShip;\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Stake_Localised\": {"]
#[doc = "      \"title\": \"Stake_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"System Colonisation Ship\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"WonDays\": {"]
#[doc = "      \"title\": \"WonDays\","]
#[doc = "      \"examples\": ["]
#[doc = "        0,"]
#[doc = "        4,"]
#[doc = "        1"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct Faction2 {
    #[serde(rename = "Name")]
    pub name: ::std::string::String,
    #[serde(rename = "Stake")]
    pub stake: ::std::string::String,
    #[serde(
        rename = "Stake_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub stake_localised: ::std::option::Option<::std::string::String>,
    #[serde(rename = "WonDays")]
    pub won_days: i64,
}
impl ::std::convert::From<&Faction2> for Faction2 {
    fn from(value: &Faction2) -> Self {
        value.clone()
    }
}
#[doc = "`FactionsItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Allegiance\","]
#[doc = "    \"FactionState\","]
#[doc = "    \"Government\","]
#[doc = "    \"Happiness\","]
#[doc = "    \"Influence\","]
#[doc = "    \"MyReputation\","]
#[doc = "    \"Name\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"ActiveStates\": {"]
#[doc = "      \"title\": \"ActiveStates\","]
#[doc = "      \"description\": \"Array with State names (Note active states do not have a Trend value)\","]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"State\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"State\": {"]
#[doc = "            \"title\": \"State\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Boom\","]
#[doc = "              \"Investment\","]
#[doc = "              \"Expansion\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"Allegiance\": {"]
#[doc = "      \"title\": \"Allegiance\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Independent\","]
#[doc = "        \"Federation\","]
#[doc = "        \"Empire\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"FactionState\": {"]
#[doc = "      \"title\": \"FactionState\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Boom\","]
#[doc = "        \"Investment\","]
#[doc = "        \"None\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Government\": {"]
#[doc = "      \"title\": \"Government\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Patronage\","]
#[doc = "        \"Cooperative\","]
#[doc = "        \"Democracy\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"HappiestSystem\": {"]
#[doc = "      \"title\": \"HappiestSystem\","]
#[doc = "      \"description\": \"If player squadron faction, and this is happiest system\","]
#[doc = "      \"examples\": ["]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"Happiness\": {"]
#[doc = "      \"title\": \"Happiness\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"$Faction_HappinessBand2;\","]
#[doc = "        \"$Faction_HappinessBand3;\","]
#[doc = "        \"$Faction_HappinessBand1;\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Happiness_Localised\": {"]
#[doc = "      \"title\": \"Happiness_Localised\","]
#[doc = "      \"description\": \"Happiness values are: Elated, Happy, Discontented, Unhappy, Despondent\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Happy\","]
#[doc = "        \"Discontented\","]
#[doc = "        \"Elated\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"HomeSystem\": {"]
#[doc = "      \"title\": \"HomeSystem\","]
#[doc = "      \"description\": \"If player squadron faction, and this is home system\","]
#[doc = "      \"examples\": ["]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"Influence\": {"]
#[doc = "      \"title\": \"Influence\","]
#[doc = "      \"examples\": ["]
#[doc = "        0.118881,"]
#[doc = "        0.183816,"]
#[doc = "        0.566434"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"MyReputation\": {"]
#[doc = "      \"title\": \"MyReputation\","]
#[doc = "      \"examples\": ["]
#[doc = "        0.0,"]
#[doc = "        25.818399,"]
#[doc = "        60.496498"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"Name\": {"]
#[doc = "      \"title\": \"Name\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Anti Xeno Initiative\","]
#[doc = "        \"The Hive\","]
#[doc = "        \"Operation Ida\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"PendingStates\": {"]
#[doc = "      \"title\": \"PendingStates\","]
#[doc = "      \"description\": \"Array (if any) with State name and Trend value\","]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"State\","]
#[doc = "          \"Trend\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"State\": {"]
#[doc = "            \"title\": \"State\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Expansion\","]
#[doc = "              \"CivilWar\","]
#[doc = "              \"Outbreak\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Trend\": {"]
#[doc = "            \"title\": \"Trend\","]
#[doc = "            \"examples\": ["]
#[doc = "              0"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"RecoveringStates\": {"]
#[doc = "      \"title\": \"RecoveringStates\","]
#[doc = "      \"description\": \"Array (if any) with State name and Trend value\","]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"State\","]
#[doc = "          \"Trend\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"State\": {"]
#[doc = "            \"title\": \"State\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"PublicHoliday\","]
#[doc = "              \"Outbreak\","]
#[doc = "              \"Boom\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Trend\": {"]
#[doc = "            \"title\": \"Trend\","]
#[doc = "            \"examples\": ["]
#[doc = "              0"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"SquadronFaction\": {"]
#[doc = "      \"title\": \"SquadronFaction\","]
#[doc = "      \"description\": \"If player is in squadron aligned to this faction\","]
#[doc = "      \"examples\": ["]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct FactionsItem {
    #[doc = "Array with State names (Note active states do not have a Trend value)"]
    #[serde(
        rename = "ActiveStates",
        default,
        skip_serializing_if = "::std::vec::Vec::is_empty"
    )]
    pub active_states: ::std::vec::Vec<ActiveStatesItem>,
    #[serde(rename = "Allegiance")]
    pub allegiance: ::std::string::String,
    #[serde(rename = "FactionState")]
    pub faction_state: ::std::string::String,
    #[serde(rename = "Government")]
    pub government: ::std::string::String,
    #[doc = "If player squadron faction, and this is happiest system"]
    #[serde(
        rename = "HappiestSystem",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub happiest_system: ::std::option::Option<bool>,
    #[serde(rename = "Happiness")]
    pub happiness: ::std::string::String,
    #[doc = "Happiness values are: Elated, Happy, Discontented, Unhappy, Despondent"]
    #[serde(
        rename = "Happiness_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub happiness_localised: ::std::option::Option<::std::string::String>,
    #[doc = "If player squadron faction, and this is home system"]
    #[serde(
        rename = "HomeSystem",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub home_system: ::std::option::Option<bool>,
    #[serde(rename = "Influence")]
    pub influence: f64,
    #[serde(rename = "MyReputation")]
    pub my_reputation: f64,
    #[serde(rename = "Name")]
    pub name: ::std::string::String,
    #[doc = "Array (if any) with State name and Trend value"]
    #[serde(
        rename = "PendingStates",
        default,
        skip_serializing_if = "::std::vec::Vec::is_empty"
    )]
    pub pending_states: ::std::vec::Vec<PendingStatesItem>,
    #[doc = "Array (if any) with State name and Trend value"]
    #[serde(
        rename = "RecoveringStates",
        default,
        skip_serializing_if = "::std::vec::Vec::is_empty"
    )]
    pub recovering_states: ::std::vec::Vec<RecoveringStatesItem>,
    #[doc = "If player is in squadron aligned to this faction"]
    #[serde(
        rename = "SquadronFaction",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub squadron_faction: ::std::option::Option<bool>,
}
impl ::std::convert::From<&FactionsItem> for FactionsItem {
    fn from(value: &FactionsItem) -> Self {
        value.clone()
    }
}
#[doc = "When written: when jumping from one star system to another"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"description\": \"When written: when jumping from one star system to another\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Body\","]
#[doc = "    \"BodyID\","]
#[doc = "    \"BodyType\","]
#[doc = "    \"FuelLevel\","]
#[doc = "    \"FuelUsed\","]
#[doc = "    \"JumpDist\","]
#[doc = "    \"Population\","]
#[doc = "    \"StarPos\","]
#[doc = "    \"StarSystem\","]
#[doc = "    \"SystemAddress\","]
#[doc = "    \"SystemAllegiance\","]
#[doc = "    \"SystemEconomy\","]
#[doc = "    \"SystemGovernment\","]
#[doc = "    \"SystemSecondEconomy\","]
#[doc = "    \"SystemSecurity\","]
#[doc = "    \"event\","]
#[doc = "    \"timestamp\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Body\": {"]
#[doc = "      \"title\": \"Body\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Celaeno\","]
#[doc = "        \"Tascheter Sector EL-Y b5\","]
#[doc = "        \"LHS 1443 A\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"BodyID\": {"]
#[doc = "      \"title\": \"BodyID\","]
#[doc = "      \"examples\": ["]
#[doc = "        0,"]
#[doc = "        1,"]
#[doc = "        2"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"BodyType\": {"]
#[doc = "      \"title\": \"BodyType\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Star\","]
#[doc = "        \"Null\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"BoostUsed\": {"]
#[doc = "      \"title\": \"BoostUsed\","]
#[doc = "      \"description\": \"Whether FSD boost was used\","]
#[doc = "      \"examples\": ["]
#[doc = "        4,"]
#[doc = "        1,"]
#[doc = "        3"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Conflicts\": {"]
#[doc = "      \"title\": \"Conflicts\","]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"Faction1\","]
#[doc = "          \"Faction2\","]
#[doc = "          \"Status\","]
#[doc = "          \"WarType\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"Faction1\": {"]
#[doc = "            \"title\": \"Faction1\","]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"required\": ["]
#[doc = "              \"Name\","]
#[doc = "              \"Stake\","]
#[doc = "              \"WonDays\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"Name\": {"]
#[doc = "                \"title\": \"Name\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"United HIP 20485 Future\","]
#[doc = "                  \"Gucumadhyas Incorporated\","]
#[doc = "                  \"Alliance of Wadjang\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              },"]
#[doc = "              \"Stake\": {"]
#[doc = "                \"title\": \"Stake\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"SAAvedra Depot\","]
#[doc = "                  \"Sagan Landing\","]
#[doc = "                  \"$EXT_PANEL_ColonisationShip;\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              },"]
#[doc = "              \"Stake_Localised\": {"]
#[doc = "                \"title\": \"Stake_Localised\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"System Colonisation Ship\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              },"]
#[doc = "              \"WonDays\": {"]
#[doc = "                \"title\": \"WonDays\","]
#[doc = "                \"examples\": ["]
#[doc = "                  0,"]
#[doc = "                  1,"]
#[doc = "                  2"]
#[doc = "                ],"]
#[doc = "                \"type\": \"integer\""]
#[doc = "              }"]
#[doc = "            },"]
#[doc = "            \"additionalProperties\": false"]
#[doc = "          },"]
#[doc = "          \"Faction2\": {"]
#[doc = "            \"title\": \"Faction2\","]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"required\": ["]
#[doc = "              \"Name\","]
#[doc = "              \"Stake\","]
#[doc = "              \"WonDays\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"Name\": {"]
#[doc = "                \"title\": \"Name\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"HIP 20485 Corp.\","]
#[doc = "                  \"Bureau of Gucumadhyas Liberty Party\","]
#[doc = "                  \"Asooraja Netcoms Inc\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              },"]
#[doc = "              \"Stake\": {"]
#[doc = "                \"title\": \"Stake\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"SAAvedra Depot\","]
#[doc = "                  \"Sagan Landing\","]
#[doc = "                  \"$EXT_PANEL_ColonisationShip;\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              },"]
#[doc = "              \"Stake_Localised\": {"]
#[doc = "                \"title\": \"Stake_Localised\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"System Colonisation Ship\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              },"]
#[doc = "              \"WonDays\": {"]
#[doc = "                \"title\": \"WonDays\","]
#[doc = "                \"examples\": ["]
#[doc = "                  0,"]
#[doc = "                  4,"]
#[doc = "                  1"]
#[doc = "                ],"]
#[doc = "                \"type\": \"integer\""]
#[doc = "              }"]
#[doc = "            },"]
#[doc = "            \"additionalProperties\": false"]
#[doc = "          },"]
#[doc = "          \"Status\": {"]
#[doc = "            \"title\": \"Status\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"active\","]
#[doc = "              \"pending\","]
#[doc = "              \"\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"WarType\": {"]
#[doc = "            \"title\": \"WarType\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"civilwar\","]
#[doc = "              \"war\","]
#[doc = "              \"election\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"ControllingPower\": {"]
#[doc = "      \"title\": \"ControllingPower\","]
#[doc = "      \"description\": \"Controlling power for the system\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Zachary Hudson\","]
#[doc = "        \"Yuri Grom\","]
#[doc = "        \"Li Yong-Rui\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Factions\": {"]
#[doc = "      \"title\": \"Factions\","]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"Allegiance\","]
#[doc = "          \"FactionState\","]
#[doc = "          \"Government\","]
#[doc = "          \"Happiness\","]
#[doc = "          \"Influence\","]
#[doc = "          \"MyReputation\","]
#[doc = "          \"Name\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"ActiveStates\": {"]
#[doc = "            \"title\": \"ActiveStates\","]
#[doc = "            \"description\": \"Array with State names (Note active states do not have a Trend value)\","]
#[doc = "            \"type\": \"array\","]
#[doc = "            \"items\": {"]
#[doc = "              \"type\": \"object\","]
#[doc = "              \"required\": ["]
#[doc = "                \"State\""]
#[doc = "              ],"]
#[doc = "              \"properties\": {"]
#[doc = "                \"State\": {"]
#[doc = "                  \"title\": \"State\","]
#[doc = "                  \"examples\": ["]
#[doc = "                    \"Boom\","]
#[doc = "                    \"Investment\","]
#[doc = "                    \"Expansion\""]
#[doc = "                  ],"]
#[doc = "                  \"type\": \"string\""]
#[doc = "                }"]
#[doc = "              },"]
#[doc = "              \"additionalProperties\": false"]
#[doc = "            }"]
#[doc = "          },"]
#[doc = "          \"Allegiance\": {"]
#[doc = "            \"title\": \"Allegiance\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Independent\","]
#[doc = "              \"Federation\","]
#[doc = "              \"Empire\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"FactionState\": {"]
#[doc = "            \"title\": \"FactionState\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Boom\","]
#[doc = "              \"Investment\","]
#[doc = "              \"None\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Government\": {"]
#[doc = "            \"title\": \"Government\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Patronage\","]
#[doc = "              \"Cooperative\","]
#[doc = "              \"Democracy\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"HappiestSystem\": {"]
#[doc = "            \"title\": \"HappiestSystem\","]
#[doc = "            \"description\": \"If player squadron faction, and this is happiest system\","]
#[doc = "            \"examples\": ["]
#[doc = "              true"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          },"]
#[doc = "          \"Happiness\": {"]
#[doc = "            \"title\": \"Happiness\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"$Faction_HappinessBand2;\","]
#[doc = "              \"$Faction_HappinessBand3;\","]
#[doc = "              \"$Faction_HappinessBand1;\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Happiness_Localised\": {"]
#[doc = "            \"title\": \"Happiness_Localised\","]
#[doc = "            \"description\": \"Happiness values are: Elated, Happy, Discontented, Unhappy, Despondent\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Happy\","]
#[doc = "              \"Discontented\","]
#[doc = "              \"Elated\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"HomeSystem\": {"]
#[doc = "            \"title\": \"HomeSystem\","]
#[doc = "            \"description\": \"If player squadron faction, and this is home system\","]
#[doc = "            \"examples\": ["]
#[doc = "              true"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          },"]
#[doc = "          \"Influence\": {"]
#[doc = "            \"title\": \"Influence\","]
#[doc = "            \"examples\": ["]
#[doc = "              0.118881,"]
#[doc = "              0.183816,"]
#[doc = "              0.566434"]
#[doc = "            ],"]
#[doc = "            \"type\": \"number\""]
#[doc = "          },"]
#[doc = "          \"MyReputation\": {"]
#[doc = "            \"title\": \"MyReputation\","]
#[doc = "            \"examples\": ["]
#[doc = "              0.0,"]
#[doc = "              25.818399,"]
#[doc = "              60.496498"]
#[doc = "            ],"]
#[doc = "            \"type\": \"number\""]
#[doc = "          },"]
#[doc = "          \"Name\": {"]
#[doc = "            \"title\": \"Name\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Anti Xeno Initiative\","]
#[doc = "              \"The Hive\","]
#[doc = "              \"Operation Ida\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"PendingStates\": {"]
#[doc = "            \"title\": \"PendingStates\","]
#[doc = "            \"description\": \"Array (if any) with State name and Trend value\","]
#[doc = "            \"type\": \"array\","]
#[doc = "            \"items\": {"]
#[doc = "              \"type\": \"object\","]
#[doc = "              \"required\": ["]
#[doc = "                \"State\","]
#[doc = "                \"Trend\""]
#[doc = "              ],"]
#[doc = "              \"properties\": {"]
#[doc = "                \"State\": {"]
#[doc = "                  \"title\": \"State\","]
#[doc = "                  \"examples\": ["]
#[doc = "                    \"Expansion\","]
#[doc = "                    \"CivilWar\","]
#[doc = "                    \"Outbreak\""]
#[doc = "                  ],"]
#[doc = "                  \"type\": \"string\""]
#[doc = "                },"]
#[doc = "                \"Trend\": {"]
#[doc = "                  \"title\": \"Trend\","]
#[doc = "                  \"examples\": ["]
#[doc = "                    0"]
#[doc = "                  ],"]
#[doc = "                  \"type\": \"integer\""]
#[doc = "                }"]
#[doc = "              },"]
#[doc = "              \"additionalProperties\": false"]
#[doc = "            }"]
#[doc = "          },"]
#[doc = "          \"RecoveringStates\": {"]
#[doc = "            \"title\": \"RecoveringStates\","]
#[doc = "            \"description\": \"Array (if any) with State name and Trend value\","]
#[doc = "            \"type\": \"array\","]
#[doc = "            \"items\": {"]
#[doc = "              \"type\": \"object\","]
#[doc = "              \"required\": ["]
#[doc = "                \"State\","]
#[doc = "                \"Trend\""]
#[doc = "              ],"]
#[doc = "              \"properties\": {"]
#[doc = "                \"State\": {"]
#[doc = "                  \"title\": \"State\","]
#[doc = "                  \"examples\": ["]
#[doc = "                    \"PublicHoliday\","]
#[doc = "                    \"Outbreak\","]
#[doc = "                    \"Boom\""]
#[doc = "                  ],"]
#[doc = "                  \"type\": \"string\""]
#[doc = "                },"]
#[doc = "                \"Trend\": {"]
#[doc = "                  \"title\": \"Trend\","]
#[doc = "                  \"examples\": ["]
#[doc = "                    0"]
#[doc = "                  ],"]
#[doc = "                  \"type\": \"integer\""]
#[doc = "                }"]
#[doc = "              },"]
#[doc = "              \"additionalProperties\": false"]
#[doc = "            }"]
#[doc = "          },"]
#[doc = "          \"SquadronFaction\": {"]
#[doc = "            \"title\": \"SquadronFaction\","]
#[doc = "            \"description\": \"If player is in squadron aligned to this faction\","]
#[doc = "            \"examples\": ["]
#[doc = "              true"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"FuelLevel\": {"]
#[doc = "      \"title\": \"FuelLevel\","]
#[doc = "      \"examples\": ["]
#[doc = "        30.486679,"]
#[doc = "        27.156359,"]
#[doc = "        22.441418"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"FuelUsed\": {"]
#[doc = "      \"title\": \"FuelUsed\","]
#[doc = "      \"examples\": ["]
#[doc = "        0.126384,"]
#[doc = "        4.843642,"]
#[doc = "        4.714942"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"JumpDist\": {"]
#[doc = "      \"title\": \"JumpDist\","]
#[doc = "      \"description\": \"Distance jumped\","]
#[doc = "      \"examples\": ["]
#[doc = "        5.701,"]
#[doc = "        55.359,"]
#[doc = "        55.446"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"Multicrew\": {"]
#[doc = "      \"title\": \"Multicrew\","]
#[doc = "      \"description\": \"True when inside another player's ship\","]
#[doc = "      \"examples\": ["]
#[doc = "        false"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"Population\": {"]
#[doc = "      \"title\": \"Population\","]
#[doc = "      \"examples\": ["]
#[doc = "        1200000,"]
#[doc = "        0,"]
#[doc = "        2654856"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"PowerplayConflictProgress\": {"]
#[doc = "      \"title\": \"PowerplayConflictProgress\","]
#[doc = "      \"description\": \"When the system is unoccupied and 1 or more powers are fighting for control by reaching 120k merits.\","]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"ConflictProgress\","]
#[doc = "          \"Power\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"ConflictProgress\": {"]
#[doc = "            \"title\": \"ConflictProgress\","]
#[doc = "            \"description\": \"Progress towards the control threshold of 120k merits. can exceed 100%(1.0).\","]
#[doc = "            \"examples\": ["]
#[doc = "              0.047725,"]
#[doc = "              4.1"]
#[doc = "            ],"]
#[doc = "            \"type\": \"number\""]
#[doc = "          },"]
#[doc = "          \"Power\": {"]
#[doc = "            \"title\": \"Power\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Felicia Winters\","]
#[doc = "              \"Zemina Torval\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"PowerplayState\": {"]
#[doc = "      \"title\": \"PowerplayState\","]
#[doc = "      \"description\": \"Powerplay state for the system.\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Unoccupied\","]
#[doc = "        \"Contested\","]
#[doc = "        \"Exploited\","]
#[doc = "        \"Fortified\","]
#[doc = "        \"Stronghold\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"PowerplayStateControlProgress\": {"]
#[doc = "      \"title\": \"PowerplayStateControlProgress\","]
#[doc = "      \"description\": \"The current amount of control within the specific powerplay state\","]
#[doc = "      \"examples\": ["]
#[doc = "        0.753582"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"PowerplayStateReinforcement\": {"]
#[doc = "      \"title\": \"PowerplayStateReinforcement\","]
#[doc = "      \"description\": \"Merits gained towards reinforcing the system and increasing the system strength\","]
#[doc = "      \"examples\": ["]
#[doc = "        296"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"PowerplayStateUndermining\": {"]
#[doc = "      \"title\": \"PowerplayStateUndermining\","]
#[doc = "      \"description\": \"Merits gained towards undermining the system and decreasing the system strength\","]
#[doc = "      \"examples\": ["]
#[doc = "        1942"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Powers\": {"]
#[doc = "      \"title\": \"Powers\","]
#[doc = "      \"description\": \"If the player is pledged to a Power in Powerplay, and the star system is involved in powerplay\","]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"examples\": ["]
#[doc = "          \"Zachary Hudson\","]
#[doc = "          \"Yuri Grom\","]
#[doc = "          \"Li Yong-Rui\""]
#[doc = "        ],"]
#[doc = "        \"type\": \"string\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"StarPos\": {"]
#[doc = "      \"title\": \"StarPos\","]
#[doc = "      \"description\": \"star position, as a Json array [x, y, z], relative to Sol in Ly\","]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"examples\": ["]
#[doc = "          -81.09375,"]
#[doc = "          -148.3125,"]
#[doc = "          -337.09375"]
#[doc = "        ],"]
#[doc = "        \"type\": \"number\""]
#[doc = "      },"]
#[doc = "      \"maxItems\": 3,"]
#[doc = "      \"minItems\": 3"]
#[doc = "    },"]
#[doc = "    \"StarSystem\": {"]
#[doc = "      \"title\": \"StarSystem\","]
#[doc = "      \"description\": \"Name of destination starsystem\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Celaeno\","]
#[doc = "        \"Tascheter Sector EL-Y b5\","]
#[doc = "        \"LHS 1443\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"SystemAddress\": {"]
#[doc = "      \"title\": \"SystemAddress\","]
#[doc = "      \"examples\": ["]
#[doc = "        198875014308,"]
#[doc = "        11665802143105,"]
#[doc = "        5068732442009"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"SystemAllegiance\": {"]
#[doc = "      \"title\": \"SystemAllegiance\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Independent\","]
#[doc = "        \"\","]
#[doc = "        \"Empire\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"SystemEconomy\": {"]
#[doc = "      \"title\": \"SystemEconomy\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"$economy_Industrial;\","]
#[doc = "        \"$economy_None;\","]
#[doc = "        \"$economy_Refinery;\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"SystemEconomy_Localised\": {"]
#[doc = "      \"title\": \"SystemEconomy_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Industrial\","]
#[doc = "        \"None\","]
#[doc = "        \"Refinery\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"SystemFaction\": {"]
#[doc = "      \"title\": \"SystemFaction\","]
#[doc = "      \"description\": \"System controlling faction\","]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"Name\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"FactionState\": {"]
#[doc = "          \"title\": \"FactionState\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"Investment\","]
#[doc = "            \"Boom\","]
#[doc = "            \"Expansion\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"Name\": {"]
#[doc = "          \"title\": \"Name\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"Operation Ida\","]
#[doc = "            \"Knights of Karma\","]
#[doc = "            \"Pilot Syndicate 4\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"additionalProperties\": false"]
#[doc = "    },"]
#[doc = "    \"SystemGovernment\": {"]
#[doc = "      \"title\": \"SystemGovernment\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"$government_Cooperative;\","]
#[doc = "        \"$government_None;\","]
#[doc = "        \"$government_Feudal;\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"SystemGovernment_Localised\": {"]
#[doc = "      \"title\": \"SystemGovernment_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Cooperative\","]
#[doc = "        \"None\","]
#[doc = "        \"Feudal\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"SystemSecondEconomy\": {"]
#[doc = "      \"title\": \"SystemSecondEconomy\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"$economy_None;\","]
#[doc = "        \"$economy_Industrial;\","]
#[doc = "        \"$economy_Extraction;\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"SystemSecondEconomy_Localised\": {"]
#[doc = "      \"title\": \"SystemSecondEconomy_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"None\","]
#[doc = "        \"Industrial\","]
#[doc = "        \"Extraction\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"SystemSecurity\": {"]
#[doc = "      \"title\": \"SystemSecurity\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"$SYSTEM_SECURITY_low;\","]
#[doc = "        \"$GAlAXY_MAP_INFO_state_anarchy;\","]
#[doc = "        \"$SYSTEM_SECURITY_medium;\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"SystemSecurity_Localised\": {"]
#[doc = "      \"title\": \"SystemSecurity_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Low Security\","]
#[doc = "        \"Anarchy\","]
#[doc = "        \"Medium Security\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Taxi\": {"]
#[doc = "      \"title\": \"Taxi\","]
#[doc = "      \"description\": \"True when inside a taxi transport ship\","]
#[doc = "      \"examples\": ["]
#[doc = "        false,"]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"ThargoidWar\": {"]
#[doc = "      \"title\": \"ThargoidWar\","]
#[doc = "      \"description\": \"Thargoid war information\","]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"CurrentState\","]
#[doc = "        \"SuccessStateReached\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"CurrentState\": {"]
#[doc = "          \"title\": \"CurrentState\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"Thargoid_Probing\","]
#[doc = "            \"Thargoid_Harvest\","]
#[doc = "            \"Thargoid_Controlled\","]
#[doc = "            \"Thargoid_Stronghold\","]
#[doc = "            \"Thargoid_Recovery\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"EstimatedRemainingTime\": {"]
#[doc = "          \"title\": \"EstimatedRemainingTime\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"1 Days\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"NextStateFailure\": {"]
#[doc = "          \"title\": \"NextStateFailure\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"Thargoid_Probing\","]
#[doc = "            \"Thargoid_Harvest\","]
#[doc = "            \"Thargoid_Controlled\","]
#[doc = "            \"Thargoid_Stronghold\","]
#[doc = "            \"Thargoid_Recovery\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"NextStateSuccess\": {"]
#[doc = "          \"title\": \"NextStateSuccess\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"Thargoid_Probing\","]
#[doc = "            \"Thargoid_Harvest\","]
#[doc = "            \"Thargoid_Controlled\","]
#[doc = "            \"Thargoid_Stronghold\","]
#[doc = "            \"Thargoid_Recovery\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"RemainingPorts\": {"]
#[doc = "          \"title\": \"RemainingPorts\","]
#[doc = "          \"examples\": ["]
#[doc = "            1"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"SuccessStateReached\": {"]
#[doc = "          \"title\": \"SuccessStateReached\","]
#[doc = "          \"examples\": ["]
#[doc = "            true,"]
#[doc = "            false"]
#[doc = "          ],"]
#[doc = "          \"type\": \"boolean\""]
#[doc = "        },"]
#[doc = "        \"WarProgress\": {"]
#[doc = "          \"title\": \"WarProgress\","]
#[doc = "          \"examples\": ["]
#[doc = "            0.15"]
#[doc = "          ],"]
#[doc = "          \"type\": \"number\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"additionalProperties\": false"]
#[doc = "    },"]
#[doc = "    \"Wanted\": {"]
#[doc = "      \"title\": \"Wanted\","]
#[doc = "      \"examples\": ["]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"event\": {"]
#[doc = "      \"title\": \"event\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"AfmuRepairs\","]
#[doc = "        \"FSDJump\","]
#[doc = "        \"Location\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"timestamp\": {"]
#[doc = "      \"title\": \"timestamp\","]
#[doc = "      \"description\": \"Timestamp in UTC, ISO 8601\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"2022-09-11T22:00:45Z\","]
#[doc = "        \"2022-09-12T08:54:21Z\","]
#[doc = "        \"2022-09-12T08:54:24Z\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"format\": \"date-time\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct FSDJump {
    #[serde(rename = "Body")]
    pub body: ::std::string::String,
    #[serde(rename = "BodyID")]
    pub body_id: i64,
    #[serde(rename = "BodyType")]
    pub body_type: ::std::string::String,
    #[doc = "Whether FSD boost was used"]
    #[serde(
        rename = "BoostUsed",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub boost_used: ::std::option::Option<i64>,
    #[serde(
        rename = "Conflicts",
        default,
        skip_serializing_if = "::std::vec::Vec::is_empty"
    )]
    pub conflicts: ::std::vec::Vec<ConflictsItem>,
    #[doc = "Controlling power for the system"]
    #[serde(
        rename = "ControllingPower",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub controlling_power: ::std::option::Option<::std::string::String>,
    #[serde(skip_deserializing, default = "FSDJump::event_value")]
    pub event: String,
    #[serde(
        rename = "Factions",
        default,
        skip_serializing_if = "::std::vec::Vec::is_empty"
    )]
    pub factions: ::std::vec::Vec<FactionsItem>,
    #[serde(rename = "FuelLevel")]
    pub fuel_level: f64,
    #[serde(rename = "FuelUsed")]
    pub fuel_used: f64,
    #[serde(rename = "JumpDist")]
    pub jump_dist: f64,
    #[doc = "True when inside another player's ship"]
    #[serde(
        rename = "Multicrew",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub multicrew: ::std::option::Option<bool>,
    #[serde(rename = "Population")]
    pub population: i64,
    #[doc = "When the system is unoccupied and 1 or more powers are fighting for control by reaching 120k merits."]
    #[serde(
        rename = "PowerplayConflictProgress",
        default,
        skip_serializing_if = "::std::vec::Vec::is_empty"
    )]
    pub powerplay_conflict_progress: ::std::vec::Vec<PowerplayConflictProgressItem>,
    #[doc = "Powerplay state for the system."]
    #[serde(
        rename = "PowerplayState",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub powerplay_state: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "PowerplayStateControlProgress",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub powerplay_state_control_progress: ::std::option::Option<f64>,
    #[doc = "Merits gained towards reinforcing the system and increasing the system strength"]
    #[serde(
        rename = "PowerplayStateReinforcement",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub powerplay_state_reinforcement: ::std::option::Option<i64>,
    #[doc = "Merits gained towards undermining the system and decreasing the system strength"]
    #[serde(
        rename = "PowerplayStateUndermining",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub powerplay_state_undermining: ::std::option::Option<i64>,
    #[doc = "If the player is pledged to a Power in Powerplay, and the star system is involved in powerplay"]
    #[serde(
        rename = "Powers",
        default,
        skip_serializing_if = "::std::vec::Vec::is_empty"
    )]
    pub powers: ::std::vec::Vec<::std::string::String>,
    #[doc = "star position, as a Json array [x, y, z], relative to Sol in Ly"]
    #[serde(rename = "StarPos")]
    pub star_pos: [f64; 3usize],
    #[doc = "Name of destination starsystem"]
    #[serde(rename = "StarSystem")]
    pub star_system: ::std::string::String,
    #[serde(rename = "SystemAddress")]
    pub system_address: i64,
    #[serde(rename = "SystemAllegiance")]
    pub system_allegiance: ::std::string::String,
    #[serde(rename = "SystemEconomy")]
    pub system_economy: ::std::string::String,
    #[serde(
        rename = "SystemEconomy_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub system_economy_localised: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "SystemFaction",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub system_faction: ::std::option::Option<SystemFaction>,
    #[serde(rename = "SystemGovernment")]
    pub system_government: ::std::string::String,
    #[serde(
        rename = "SystemGovernment_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub system_government_localised: ::std::option::Option<::std::string::String>,
    #[serde(rename = "SystemSecondEconomy")]
    pub system_second_economy: ::std::string::String,
    #[serde(
        rename = "SystemSecondEconomy_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub system_second_economy_localised: ::std::option::Option<::std::string::String>,
    #[serde(rename = "SystemSecurity")]
    pub system_security: ::std::string::String,
    #[serde(
        rename = "SystemSecurity_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub system_security_localised: ::std::option::Option<::std::string::String>,
    #[doc = "True when inside a taxi transport ship"]
    #[serde(
        rename = "Taxi",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub taxi: ::std::option::Option<bool>,
    #[serde(
        rename = "ThargoidWar",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub thargoid_war: ::std::option::Option<ThargoidWar>,
    #[doc = "Timestamp in UTC, ISO 8601"]
    pub timestamp: ::chrono::DateTime<::chrono::offset::Utc>,
    #[serde(
        rename = "Wanted",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub wanted: ::std::option::Option<bool>,
}
impl ::std::convert::From<&FSDJump> for FSDJump {
    fn from(value: &FSDJump) -> Self {
        value.clone()
    }
}
#[doc = "`PendingStatesItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"State\","]
#[doc = "    \"Trend\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"State\": {"]
#[doc = "      \"title\": \"State\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Expansion\","]
#[doc = "        \"CivilWar\","]
#[doc = "        \"Outbreak\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Trend\": {"]
#[doc = "      \"title\": \"Trend\","]
#[doc = "      \"examples\": ["]
#[doc = "        0"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PendingStatesItem {
    #[serde(rename = "State")]
    pub state: ::std::string::String,
    #[serde(rename = "Trend")]
    pub trend: i64,
}
impl ::std::convert::From<&PendingStatesItem> for PendingStatesItem {
    fn from(value: &PendingStatesItem) -> Self {
        value.clone()
    }
}
#[doc = "`PowerplayConflictProgressItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"ConflictProgress\","]
#[doc = "    \"Power\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"ConflictProgress\": {"]
#[doc = "      \"title\": \"ConflictProgress\","]
#[doc = "      \"description\": \"Progress towards the control threshold of 120k merits. can exceed 100%(1.0).\","]
#[doc = "      \"examples\": ["]
#[doc = "        0.047725,"]
#[doc = "        4.1"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"Power\": {"]
#[doc = "      \"title\": \"Power\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Felicia Winters\","]
#[doc = "        \"Zemina Torval\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PowerplayConflictProgressItem {
    #[serde(rename = "ConflictProgress")]
    pub conflict_progress: f64,
    #[serde(rename = "Power")]
    pub power: ::std::string::String,
}
impl ::std::convert::From<&PowerplayConflictProgressItem> for PowerplayConflictProgressItem {
    fn from(value: &PowerplayConflictProgressItem) -> Self {
        value.clone()
    }
}
#[doc = "`RecoveringStatesItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"State\","]
#[doc = "    \"Trend\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"State\": {"]
#[doc = "      \"title\": \"State\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"PublicHoliday\","]
#[doc = "        \"Outbreak\","]
#[doc = "        \"Boom\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Trend\": {"]
#[doc = "      \"title\": \"Trend\","]
#[doc = "      \"examples\": ["]
#[doc = "        0"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct RecoveringStatesItem {
    #[serde(rename = "State")]
    pub state: ::std::string::String,
    #[serde(rename = "Trend")]
    pub trend: i64,
}
impl ::std::convert::From<&RecoveringStatesItem> for RecoveringStatesItem {
    fn from(value: &RecoveringStatesItem) -> Self {
        value.clone()
    }
}
#[doc = "System controlling faction"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"SystemFaction\","]
#[doc = "  \"description\": \"System controlling faction\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Name\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"FactionState\": {"]
#[doc = "      \"title\": \"FactionState\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Investment\","]
#[doc = "        \"Boom\","]
#[doc = "        \"Expansion\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Name\": {"]
#[doc = "      \"title\": \"Name\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Operation Ida\","]
#[doc = "        \"Knights of Karma\","]
#[doc = "        \"Pilot Syndicate 4\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct SystemFaction {
    #[serde(
        rename = "FactionState",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub faction_state: ::std::option::Option<::std::string::String>,
    #[serde(rename = "Name")]
    pub name: ::std::string::String,
}
impl ::std::convert::From<&SystemFaction> for SystemFaction {
    fn from(value: &SystemFaction) -> Self {
        value.clone()
    }
}
#[doc = "Thargoid war information"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"ThargoidWar\","]
#[doc = "  \"description\": \"Thargoid war information\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"CurrentState\","]
#[doc = "    \"SuccessStateReached\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"CurrentState\": {"]
#[doc = "      \"title\": \"CurrentState\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Thargoid_Probing\","]
#[doc = "        \"Thargoid_Harvest\","]
#[doc = "        \"Thargoid_Controlled\","]
#[doc = "        \"Thargoid_Stronghold\","]
#[doc = "        \"Thargoid_Recovery\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"EstimatedRemainingTime\": {"]
#[doc = "      \"title\": \"EstimatedRemainingTime\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"1 Days\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"NextStateFailure\": {"]
#[doc = "      \"title\": \"NextStateFailure\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Thargoid_Probing\","]
#[doc = "        \"Thargoid_Harvest\","]
#[doc = "        \"Thargoid_Controlled\","]
#[doc = "        \"Thargoid_Stronghold\","]
#[doc = "        \"Thargoid_Recovery\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"NextStateSuccess\": {"]
#[doc = "      \"title\": \"NextStateSuccess\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Thargoid_Probing\","]
#[doc = "        \"Thargoid_Harvest\","]
#[doc = "        \"Thargoid_Controlled\","]
#[doc = "        \"Thargoid_Stronghold\","]
#[doc = "        \"Thargoid_Recovery\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"RemainingPorts\": {"]
#[doc = "      \"title\": \"RemainingPorts\","]
#[doc = "      \"examples\": ["]
#[doc = "        1"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"SuccessStateReached\": {"]
#[doc = "      \"title\": \"SuccessStateReached\","]
#[doc = "      \"examples\": ["]
#[doc = "        true,"]
#[doc = "        false"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"WarProgress\": {"]
#[doc = "      \"title\": \"WarProgress\","]
#[doc = "      \"examples\": ["]
#[doc = "        0.15"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ThargoidWar {
    #[serde(rename = "CurrentState")]
    pub current_state: ::std::string::String,
    #[serde(
        rename = "EstimatedRemainingTime",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub estimated_remaining_time: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "NextStateFailure",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub next_state_failure: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "NextStateSuccess",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub next_state_success: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "RemainingPorts",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub remaining_ports: ::std::option::Option<i64>,
    #[serde(rename = "SuccessStateReached")]
    pub success_state_reached: bool,
    #[serde(
        rename = "WarProgress",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub war_progress: ::std::option::Option<f64>,
}
impl ::std::convert::From<&ThargoidWar> for ThargoidWar {
    fn from(value: &ThargoidWar) -> Self {
        value.clone()
    }
}

impl FSDJump {
    pub fn event_value() -> ::std::string::String {
        "FSDJump".to_string()
    }
}
