#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "If engineered"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"Engineering\","]
#[doc = "  \"description\": \"If engineered\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"BlueprintID\","]
#[doc = "    \"BlueprintName\","]
#[doc = "    \"EngineerID\","]
#[doc = "    \"Level\","]
#[doc = "    \"Modifiers\","]
#[doc = "    \"Quality\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"BlueprintID\": {"]
#[doc = "      \"title\": \"BlueprintID\","]
#[doc = "      \"examples\": ["]
#[doc = "        128988383,"]
#[doc = "        128731666,"]
#[doc = "        128673644"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"BlueprintName\": {"]
#[doc = "      \"title\": \"BlueprintName\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Weapon_RapidFire\","]
#[doc = "        \"Misc_HeatSinkCapacity\","]
#[doc = "        \"Armour_HeavyDuty\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Engineer\": {"]
#[doc = "      \"title\": \"Engineer\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Ram Tah\","]
#[doc = "        \"Selene Jean\","]
#[doc = "        \"Hera Tani\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"EngineerID\": {"]
#[doc = "      \"title\": \"EngineerID\","]
#[doc = "      \"examples\": ["]
#[doc = "        300001,"]
#[doc = "        300110,"]
#[doc = "        300210"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"ExperimentalEffect\": {"]
#[doc = "      \"title\": \"ExperimentalEffect\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"special_armour_chunky\","]
#[doc = "        \"special_powerplant_highcharge\","]
#[doc = "        \"special_engine_overloaded\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"ExperimentalEffect_Localised\": {"]
#[doc = "      \"title\": \"ExperimentalEffect_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Deep Plating\","]
#[doc = "        \"Monstered\","]
#[doc = "        \"Drag Drives\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Level\": {"]
#[doc = "      \"title\": \"Level\","]
#[doc = "      \"examples\": ["]
#[doc = "        1,"]
#[doc = "        5,"]
#[doc = "        4"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Modifiers\": {"]
#[doc = "      \"title\": \"Modifiers\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"Label\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"Label\": {"]
#[doc = "            \"title\": \"Label\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"DamagePerSecond\","]
#[doc = "              \"Damage\","]
#[doc = "              \"DistributorDraw\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"LessIsGood\": {"]
#[doc = "            \"title\": \"LessIsGood\","]
#[doc = "            \"description\": \"Either 0 or 1\","]
#[doc = "            \"examples\": ["]
#[doc = "              0,"]
#[doc = "              1"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"OriginalValue\": {"]
#[doc = "            \"title\": \"OriginalValue\","]
#[doc = "            \"examples\": ["]
#[doc = "              46.385544,"]
#[doc = "              38.5,"]
#[doc = "              7.2"]
#[doc = "            ],"]
#[doc = "            \"type\": \"number\""]
#[doc = "          },"]
#[doc = "          \"Value\": {"]
#[doc = "            \"title\": \"Value\","]
#[doc = "            \"description\": \"Either Value or ValueStr is used. These modification types have string values: WeaponMode, DamageType, CabinClass.\","]
#[doc = "            \"examples\": ["]
#[doc = "              46.385887,"]
#[doc = "              9.542736,"]
#[doc = "              1.8"]
#[doc = "            ],"]
#[doc = "            \"type\": \"number\""]
#[doc = "          },"]
#[doc = "          \"ValueStr\": {"]
#[doc = "            \"title\": \"ValueStr\","]
#[doc = "            \"description\": \"Either Value or ValueStr is used. These modification types have string values: WeaponMode, DamageType, CabinClass.\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"$Thermic;\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"ValueStr_Localised\": {"]
#[doc = "            \"title\": \"ValueStr_Localised\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Thermal\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"Quality\": {"]
#[doc = "      \"title\": \"Quality\","]
#[doc = "      \"examples\": ["]
#[doc = "        0.0,"]
#[doc = "        1.0,"]
#[doc = "        0.98"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct Engineering {
    #[serde(rename = "BlueprintID")]
    pub blueprint_id: i64,
    #[serde(rename = "BlueprintName")]
    pub blueprint_name: ::std::string::String,
    #[serde(
        rename = "Engineer",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub engineer: ::std::option::Option<::std::string::String>,
    #[serde(rename = "EngineerID")]
    pub engineer_id: i64,
    #[serde(
        rename = "ExperimentalEffect",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub experimental_effect: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "ExperimentalEffect_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub experimental_effect_localised: ::std::option::Option<::std::string::String>,
    #[serde(rename = "Level")]
    pub level: i64,
    #[serde(rename = "Modifiers")]
    pub modifiers: ::std::vec::Vec<ModifiersItem>,
    #[serde(rename = "Quality")]
    pub quality: f64,
}
impl ::std::convert::From<&Engineering> for Engineering {
    fn from(value: &Engineering) -> Self {
        value.clone()
    }
}
#[doc = "`FuelCapacity`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"FuelCapacity\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Main\","]
#[doc = "    \"Reserve\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Main\": {"]
#[doc = "      \"title\": \"Main\","]
#[doc = "      \"examples\": ["]
#[doc = "        32.0,"]
#[doc = "        64.0,"]
#[doc = "        16.0"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"Reserve\": {"]
#[doc = "      \"title\": \"Reserve\","]
#[doc = "      \"examples\": ["]
#[doc = "        0.63,"]
#[doc = "        1.16,"]
#[doc = "        0.74"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct FuelCapacity {
    #[serde(rename = "Main")]
    pub main: f64,
    #[serde(rename = "Reserve")]
    pub reserve: f64,
}
impl ::std::convert::From<&FuelCapacity> for FuelCapacity {
    fn from(value: &FuelCapacity) -> Self {
        value.clone()
    }
}
#[doc = "When written: at startup, when loading from main menu, or when switching ships, or after changing the ship in Outfitting, or when docking SRV back in mothership"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"description\": \"When written: at startup, when loading from main menu, or when switching ships, or after changing the ship in Outfitting, or when docking SRV back in mothership\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"CargoCapacity\","]
#[doc = "    \"FuelCapacity\","]
#[doc = "    \"HullHealth\","]
#[doc = "    \"MaxJumpRange\","]
#[doc = "    \"Modules\","]
#[doc = "    \"Rebuy\","]
#[doc = "    \"Ship\","]
#[doc = "    \"ShipID\","]
#[doc = "    \"ShipIdent\","]
#[doc = "    \"ShipName\","]
#[doc = "    \"UnladenMass\","]
#[doc = "    \"event\","]
#[doc = "    \"timestamp\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"CargoCapacity\": {"]
#[doc = "      \"title\": \"CargoCapacity\","]
#[doc = "      \"examples\": ["]
#[doc = "        16,"]
#[doc = "        48,"]
#[doc = "        0"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"FuelCapacity\": {"]
#[doc = "      \"title\": \"FuelCapacity\","]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"Main\","]
#[doc = "        \"Reserve\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"Main\": {"]
#[doc = "          \"title\": \"Main\","]
#[doc = "          \"examples\": ["]
#[doc = "            32.0,"]
#[doc = "            64.0,"]
#[doc = "            16.0"]
#[doc = "          ],"]
#[doc = "          \"type\": \"number\""]
#[doc = "        },"]
#[doc = "        \"Reserve\": {"]
#[doc = "          \"title\": \"Reserve\","]
#[doc = "          \"examples\": ["]
#[doc = "            0.63,"]
#[doc = "            1.16,"]
#[doc = "            0.74"]
#[doc = "          ],"]
#[doc = "          \"type\": \"number\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"additionalProperties\": false"]
#[doc = "    },"]
#[doc = "    \"Hot\": {"]
#[doc = "      \"title\": \"Hot\","]
#[doc = "      \"description\": \"If wanted at startup\","]
#[doc = "      \"examples\": ["]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"HullHealth\": {"]
#[doc = "      \"title\": \"HullHealth\","]
#[doc = "      \"examples\": ["]
#[doc = "        0.995647,"]
#[doc = "        1.0,"]
#[doc = "        0.761888"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"HullValue\": {"]
#[doc = "      \"title\": \"HullValue\","]
#[doc = "      \"examples\": ["]
#[doc = "        38743029,"]
#[doc = "        6136672,"]
#[doc = "        157587908"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"MaxJumpRange\": {"]
#[doc = "      \"title\": \"MaxJumpRange\","]
#[doc = "      \"description\": \"based on zero cargo, and just enough fuel for 1 jump\","]
#[doc = "      \"examples\": ["]
#[doc = "        27.032085,"]
#[doc = "        63.0658,"]
#[doc = "        63.065804"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"Modules\": {"]
#[doc = "      \"title\": \"Modules\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"Health\","]
#[doc = "          \"Item\","]
#[doc = "          \"On\","]
#[doc = "          \"Priority\","]
#[doc = "          \"Slot\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"AmmoInClip\": {"]
#[doc = "            \"title\": \"AmmoInClip\","]
#[doc = "            \"description\": \"If relevant. For a passenger cabin, AmmoInClip holds the number of places in the cabin.\","]
#[doc = "            \"examples\": ["]
#[doc = "              1,"]
#[doc = "              4,"]
#[doc = "              12"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"AmmoInHopper\": {"]
#[doc = "            \"title\": \"AmmoInHopper\","]
#[doc = "            \"description\": \"if relevant\","]
#[doc = "            \"examples\": ["]
#[doc = "              32,"]
#[doc = "              400,"]
#[doc = "              3"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"Engineering\": {"]
#[doc = "            \"title\": \"Engineering\","]
#[doc = "            \"description\": \"If engineered\","]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"required\": ["]
#[doc = "              \"BlueprintID\","]
#[doc = "              \"BlueprintName\","]
#[doc = "              \"EngineerID\","]
#[doc = "              \"Level\","]
#[doc = "              \"Modifiers\","]
#[doc = "              \"Quality\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"BlueprintID\": {"]
#[doc = "                \"title\": \"BlueprintID\","]
#[doc = "                \"examples\": ["]
#[doc = "                  128988383,"]
#[doc = "                  128731666,"]
#[doc = "                  128673644"]
#[doc = "                ],"]
#[doc = "                \"type\": \"integer\""]
#[doc = "              },"]
#[doc = "              \"BlueprintName\": {"]
#[doc = "                \"title\": \"BlueprintName\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"Weapon_RapidFire\","]
#[doc = "                  \"Misc_HeatSinkCapacity\","]
#[doc = "                  \"Armour_HeavyDuty\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              },"]
#[doc = "              \"Engineer\": {"]
#[doc = "                \"title\": \"Engineer\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"Ram Tah\","]
#[doc = "                  \"Selene Jean\","]
#[doc = "                  \"Hera Tani\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              },"]
#[doc = "              \"EngineerID\": {"]
#[doc = "                \"title\": \"EngineerID\","]
#[doc = "                \"examples\": ["]
#[doc = "                  300001,"]
#[doc = "                  300110,"]
#[doc = "                  300210"]
#[doc = "                ],"]
#[doc = "                \"type\": \"integer\""]
#[doc = "              },"]
#[doc = "              \"ExperimentalEffect\": {"]
#[doc = "                \"title\": \"ExperimentalEffect\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"special_armour_chunky\","]
#[doc = "                  \"special_powerplant_highcharge\","]
#[doc = "                  \"special_engine_overloaded\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              },"]
#[doc = "              \"ExperimentalEffect_Localised\": {"]
#[doc = "                \"title\": \"ExperimentalEffect_Localised\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"Deep Plating\","]
#[doc = "                  \"Monstered\","]
#[doc = "                  \"Drag Drives\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              },"]
#[doc = "              \"Level\": {"]
#[doc = "                \"title\": \"Level\","]
#[doc = "                \"examples\": ["]
#[doc = "                  1,"]
#[doc = "                  5,"]
#[doc = "                  4"]
#[doc = "                ],"]
#[doc = "                \"type\": \"integer\""]
#[doc = "              },"]
#[doc = "              \"Modifiers\": {"]
#[doc = "                \"title\": \"Modifiers\","]
#[doc = "                \"default\": null,"]
#[doc = "                \"type\": \"array\","]
#[doc = "                \"items\": {"]
#[doc = "                  \"type\": \"object\","]
#[doc = "                  \"required\": ["]
#[doc = "                    \"Label\""]
#[doc = "                  ],"]
#[doc = "                  \"properties\": {"]
#[doc = "                    \"Label\": {"]
#[doc = "                      \"title\": \"Label\","]
#[doc = "                      \"examples\": ["]
#[doc = "                        \"DamagePerSecond\","]
#[doc = "                        \"Damage\","]
#[doc = "                        \"DistributorDraw\""]
#[doc = "                      ],"]
#[doc = "                      \"type\": \"string\""]
#[doc = "                    },"]
#[doc = "                    \"LessIsGood\": {"]
#[doc = "                      \"title\": \"LessIsGood\","]
#[doc = "                      \"description\": \"Either 0 or 1\","]
#[doc = "                      \"examples\": ["]
#[doc = "                        0,"]
#[doc = "                        1"]
#[doc = "                      ],"]
#[doc = "                      \"type\": \"integer\""]
#[doc = "                    },"]
#[doc = "                    \"OriginalValue\": {"]
#[doc = "                      \"title\": \"OriginalValue\","]
#[doc = "                      \"examples\": ["]
#[doc = "                        46.385544,"]
#[doc = "                        38.5,"]
#[doc = "                        7.2"]
#[doc = "                      ],"]
#[doc = "                      \"type\": \"number\""]
#[doc = "                    },"]
#[doc = "                    \"Value\": {"]
#[doc = "                      \"title\": \"Value\","]
#[doc = "                      \"description\": \"Either Value or ValueStr is used. These modification types have string values: WeaponMode, DamageType, CabinClass.\","]
#[doc = "                      \"examples\": ["]
#[doc = "                        46.385887,"]
#[doc = "                        9.542736,"]
#[doc = "                        1.8"]
#[doc = "                      ],"]
#[doc = "                      \"type\": \"number\""]
#[doc = "                    },"]
#[doc = "                    \"ValueStr\": {"]
#[doc = "                      \"title\": \"ValueStr\","]
#[doc = "                      \"description\": \"Either Value or ValueStr is used. These modification types have string values: WeaponMode, DamageType, CabinClass.\","]
#[doc = "                      \"examples\": ["]
#[doc = "                        \"$Thermic;\""]
#[doc = "                      ],"]
#[doc = "                      \"type\": \"string\""]
#[doc = "                    },"]
#[doc = "                    \"ValueStr_Localised\": {"]
#[doc = "                      \"title\": \"ValueStr_Localised\","]
#[doc = "                      \"examples\": ["]
#[doc = "                        \"Thermal\""]
#[doc = "                      ],"]
#[doc = "                      \"type\": \"string\""]
#[doc = "                    }"]
#[doc = "                  },"]
#[doc = "                  \"additionalProperties\": false"]
#[doc = "                }"]
#[doc = "              },"]
#[doc = "              \"Quality\": {"]
#[doc = "                \"title\": \"Quality\","]
#[doc = "                \"examples\": ["]
#[doc = "                  0.0,"]
#[doc = "                  1.0,"]
#[doc = "                  0.98"]
#[doc = "                ],"]
#[doc = "                \"type\": \"number\""]
#[doc = "              }"]
#[doc = "            },"]
#[doc = "            \"additionalProperties\": false"]
#[doc = "          },"]
#[doc = "          \"Health\": {"]
#[doc = "            \"title\": \"Health\","]
#[doc = "            \"examples\": ["]
#[doc = "              1.0,"]
#[doc = "              0.996043,"]
#[doc = "              0.997162"]
#[doc = "            ],"]
#[doc = "            \"type\": \"number\""]
#[doc = "          },"]
#[doc = "          \"Item\": {"]
#[doc = "            \"title\": \"Item\","]
#[doc = "            \"description\": \"Module name - lowercase\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"hpt_flakmortar_turret_medium\","]
#[doc = "              \"hpt_guardian_gausscannon_fixed_medium\","]
#[doc = "              \"hpt_heatsinklauncher_turret_tiny\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"On\": {"]
#[doc = "            \"title\": \"On\","]
#[doc = "            \"examples\": ["]
#[doc = "              true,"]
#[doc = "              false"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          },"]
#[doc = "          \"Priority\": {"]
#[doc = "            \"title\": \"Priority\","]
#[doc = "            \"examples\": ["]
#[doc = "              0,"]
#[doc = "              1,"]
#[doc = "              4"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"Slot\": {"]
#[doc = "            \"title\": \"Slot\","]
#[doc = "            \"description\": \"Slot name\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"LargeHardpoint1\","]
#[doc = "              \"LargeHardpoint2\","]
#[doc = "              \"LargeHardpoint3\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Value\": {"]
#[doc = "            \"title\": \"Value\","]
#[doc = "            \"examples\": ["]
#[doc = "              1104948,"]
#[doc = "              3072,"]
#[doc = "              356556"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"ModulesValue\": {"]
#[doc = "      \"title\": \"ModulesValue\","]
#[doc = "      \"examples\": ["]
#[doc = "        103808724,"]
#[doc = "        27690569,"]
#[doc = "        27512227"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Rebuy\": {"]
#[doc = "      \"title\": \"Rebuy\","]
#[doc = "      \"examples\": ["]
#[doc = "        7127591,"]
#[doc = "        1691363,"]
#[doc = "        1682447"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Ship\": {"]
#[doc = "      \"title\": \"Ship\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"krait_mkii\","]
#[doc = "        \"asp\","]
#[doc = "        \"cutter\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"ShipID\": {"]
#[doc = "      \"title\": \"ShipID\","]
#[doc = "      \"description\": \"Ship id number (indicates which of your ships you are in)\","]
#[doc = "      \"examples\": ["]
#[doc = "        18,"]
#[doc = "        5,"]
#[doc = "        25"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"ShipIdent\": {"]
#[doc = "      \"title\": \"ShipIdent\","]
#[doc = "      \"description\": \"User-defined ship ID string\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"ASP-01\","]
#[doc = "        \"\","]
#[doc = "        \"KM2-02\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"ShipName\": {"]
#[doc = "      \"title\": \"ShipName\","]
#[doc = "      \"description\": \"User-defined ship name\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Goidgobbler\","]
#[doc = "        \"\","]
#[doc = "        \"Starhopper\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"UnladenMass\": {"]
#[doc = "      \"title\": \"UnladenMass\","]
#[doc = "      \"description\": \"Mass of Hull and Modules, excludes fuel and cargo\","]
#[doc = "      \"examples\": ["]
#[doc = "        729.0,"]
#[doc = "        340.286102,"]
#[doc = "        338.286102"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"event\": {"]
#[doc = "      \"title\": \"event\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"AfmuRepairs\","]
#[doc = "        \"FSDJump\","]
#[doc = "        \"Location\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"timestamp\": {"]
#[doc = "      \"title\": \"timestamp\","]
#[doc = "      \"description\": \"Timestamp in UTC, ISO 8601\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"2022-09-11T22:00:45Z\","]
#[doc = "        \"2022-09-12T08:54:21Z\","]
#[doc = "        \"2022-09-12T08:54:24Z\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"format\": \"date-time\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct Loadout {
    #[serde(rename = "CargoCapacity")]
    pub cargo_capacity: i64,
    #[serde(skip_deserializing, default = "Loadout::event_value")]
    pub event: String,
    #[serde(rename = "FuelCapacity")]
    pub fuel_capacity: FuelCapacity,
    #[doc = "If wanted at startup"]
    #[serde(
        rename = "Hot",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub hot: ::std::option::Option<bool>,
    #[serde(rename = "HullHealth")]
    pub hull_health: f64,
    #[serde(
        rename = "HullValue",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub hull_value: ::std::option::Option<i64>,
    #[serde(rename = "MaxJumpRange")]
    pub max_jump_range: f64,
    #[serde(rename = "Modules")]
    pub modules: ::std::vec::Vec<ModulesItem>,
    #[serde(
        rename = "ModulesValue",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub modules_value: ::std::option::Option<i64>,
    #[serde(rename = "Rebuy")]
    pub rebuy: i64,
    #[serde(rename = "Ship")]
    pub ship: ::std::string::String,
    #[doc = "Ship id number (indicates which of your ships you are in)"]
    #[serde(rename = "ShipID")]
    pub ship_id: i64,
    #[doc = "User-defined ship ID string"]
    #[serde(rename = "ShipIdent")]
    pub ship_ident: ::std::string::String,
    #[doc = "User-defined ship name"]
    #[serde(rename = "ShipName")]
    pub ship_name: ::std::string::String,
    #[doc = "Timestamp in UTC, ISO 8601"]
    pub timestamp: ::chrono::DateTime<::chrono::offset::Utc>,
    #[serde(rename = "UnladenMass")]
    pub unladen_mass: f64,
}
impl ::std::convert::From<&Loadout> for Loadout {
    fn from(value: &Loadout) -> Self {
        value.clone()
    }
}
#[doc = "`ModifiersItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Label\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Label\": {"]
#[doc = "      \"title\": \"Label\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"DamagePerSecond\","]
#[doc = "        \"Damage\","]
#[doc = "        \"DistributorDraw\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"LessIsGood\": {"]
#[doc = "      \"title\": \"LessIsGood\","]
#[doc = "      \"description\": \"Either 0 or 1\","]
#[doc = "      \"examples\": ["]
#[doc = "        0,"]
#[doc = "        1"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"OriginalValue\": {"]
#[doc = "      \"title\": \"OriginalValue\","]
#[doc = "      \"examples\": ["]
#[doc = "        46.385544,"]
#[doc = "        38.5,"]
#[doc = "        7.2"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"Value\": {"]
#[doc = "      \"title\": \"Value\","]
#[doc = "      \"description\": \"Either Value or ValueStr is used. These modification types have string values: WeaponMode, DamageType, CabinClass.\","]
#[doc = "      \"examples\": ["]
#[doc = "        46.385887,"]
#[doc = "        9.542736,"]
#[doc = "        1.8"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"ValueStr\": {"]
#[doc = "      \"title\": \"ValueStr\","]
#[doc = "      \"description\": \"Either Value or ValueStr is used. These modification types have string values: WeaponMode, DamageType, CabinClass.\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"$Thermic;\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"ValueStr_Localised\": {"]
#[doc = "      \"title\": \"ValueStr_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Thermal\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ModifiersItem {
    #[serde(rename = "Label")]
    pub label: ::std::string::String,
    #[doc = "Either 0 or 1"]
    #[serde(
        rename = "LessIsGood",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub less_is_good: ::std::option::Option<i64>,
    #[serde(
        rename = "OriginalValue",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub original_value: ::std::option::Option<f64>,
    #[serde(
        rename = "Value",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub value: ::std::option::Option<f64>,
    #[doc = "Either Value or ValueStr is used. These modification types have string values: WeaponMode, DamageType, CabinClass."]
    #[serde(
        rename = "ValueStr",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub value_str: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "ValueStr_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub value_str_localised: ::std::option::Option<::std::string::String>,
}
impl ::std::convert::From<&ModifiersItem> for ModifiersItem {
    fn from(value: &ModifiersItem) -> Self {
        value.clone()
    }
}
#[doc = "`ModulesItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Health\","]
#[doc = "    \"Item\","]
#[doc = "    \"On\","]
#[doc = "    \"Priority\","]
#[doc = "    \"Slot\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"AmmoInClip\": {"]
#[doc = "      \"title\": \"AmmoInClip\","]
#[doc = "      \"description\": \"If relevant. For a passenger cabin, AmmoInClip holds the number of places in the cabin.\","]
#[doc = "      \"examples\": ["]
#[doc = "        1,"]
#[doc = "        4,"]
#[doc = "        12"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"AmmoInHopper\": {"]
#[doc = "      \"title\": \"AmmoInHopper\","]
#[doc = "      \"description\": \"if relevant\","]
#[doc = "      \"examples\": ["]
#[doc = "        32,"]
#[doc = "        400,"]
#[doc = "        3"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Engineering\": {"]
#[doc = "      \"title\": \"Engineering\","]
#[doc = "      \"description\": \"If engineered\","]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"BlueprintID\","]
#[doc = "        \"BlueprintName\","]
#[doc = "        \"EngineerID\","]
#[doc = "        \"Level\","]
#[doc = "        \"Modifiers\","]
#[doc = "        \"Quality\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"BlueprintID\": {"]
#[doc = "          \"title\": \"BlueprintID\","]
#[doc = "          \"examples\": ["]
#[doc = "            128988383,"]
#[doc = "            128731666,"]
#[doc = "            128673644"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"BlueprintName\": {"]
#[doc = "          \"title\": \"BlueprintName\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"Weapon_RapidFire\","]
#[doc = "            \"Misc_HeatSinkCapacity\","]
#[doc = "            \"Armour_HeavyDuty\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"Engineer\": {"]
#[doc = "          \"title\": \"Engineer\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"Ram Tah\","]
#[doc = "            \"Selene Jean\","]
#[doc = "            \"Hera Tani\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"EngineerID\": {"]
#[doc = "          \"title\": \"EngineerID\","]
#[doc = "          \"examples\": ["]
#[doc = "            300001,"]
#[doc = "            300110,"]
#[doc = "            300210"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"ExperimentalEffect\": {"]
#[doc = "          \"title\": \"ExperimentalEffect\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"special_armour_chunky\","]
#[doc = "            \"special_powerplant_highcharge\","]
#[doc = "            \"special_engine_overloaded\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"ExperimentalEffect_Localised\": {"]
#[doc = "          \"title\": \"ExperimentalEffect_Localised\","]
#[doc = "          \"examples\": ["]
#[doc = "            \"Deep Plating\","]
#[doc = "            \"Monstered\","]
#[doc = "            \"Drag Drives\""]
#[doc = "          ],"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"Level\": {"]
#[doc = "          \"title\": \"Level\","]
#[doc = "          \"examples\": ["]
#[doc = "            1,"]
#[doc = "            5,"]
#[doc = "            4"]
#[doc = "          ],"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"Modifiers\": {"]
#[doc = "          \"title\": \"Modifiers\","]
#[doc = "          \"default\": null,"]
#[doc = "          \"type\": \"array\","]
#[doc = "          \"items\": {"]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"required\": ["]
#[doc = "              \"Label\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"Label\": {"]
#[doc = "                \"title\": \"Label\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"DamagePerSecond\","]
#[doc = "                  \"Damage\","]
#[doc = "                  \"DistributorDraw\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              },"]
#[doc = "              \"LessIsGood\": {"]
#[doc = "                \"title\": \"LessIsGood\","]
#[doc = "                \"description\": \"Either 0 or 1\","]
#[doc = "                \"examples\": ["]
#[doc = "                  0,"]
#[doc = "                  1"]
#[doc = "                ],"]
#[doc = "                \"type\": \"integer\""]
#[doc = "              },"]
#[doc = "              \"OriginalValue\": {"]
#[doc = "                \"title\": \"OriginalValue\","]
#[doc = "                \"examples\": ["]
#[doc = "                  46.385544,"]
#[doc = "                  38.5,"]
#[doc = "                  7.2"]
#[doc = "                ],"]
#[doc = "                \"type\": \"number\""]
#[doc = "              },"]
#[doc = "              \"Value\": {"]
#[doc = "                \"title\": \"Value\","]
#[doc = "                \"description\": \"Either Value or ValueStr is used. These modification types have string values: WeaponMode, DamageType, CabinClass.\","]
#[doc = "                \"examples\": ["]
#[doc = "                  46.385887,"]
#[doc = "                  9.542736,"]
#[doc = "                  1.8"]
#[doc = "                ],"]
#[doc = "                \"type\": \"number\""]
#[doc = "              },"]
#[doc = "              \"ValueStr\": {"]
#[doc = "                \"title\": \"ValueStr\","]
#[doc = "                \"description\": \"Either Value or ValueStr is used. These modification types have string values: WeaponMode, DamageType, CabinClass.\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"$Thermic;\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              },"]
#[doc = "              \"ValueStr_Localised\": {"]
#[doc = "                \"title\": \"ValueStr_Localised\","]
#[doc = "                \"examples\": ["]
#[doc = "                  \"Thermal\""]
#[doc = "                ],"]
#[doc = "                \"type\": \"string\""]
#[doc = "              }"]
#[doc = "            },"]
#[doc = "            \"additionalProperties\": false"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"Quality\": {"]
#[doc = "          \"title\": \"Quality\","]
#[doc = "          \"examples\": ["]
#[doc = "            0.0,"]
#[doc = "            1.0,"]
#[doc = "            0.98"]
#[doc = "          ],"]
#[doc = "          \"type\": \"number\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"additionalProperties\": false"]
#[doc = "    },"]
#[doc = "    \"Health\": {"]
#[doc = "      \"title\": \"Health\","]
#[doc = "      \"examples\": ["]
#[doc = "        1.0,"]
#[doc = "        0.996043,"]
#[doc = "        0.997162"]
#[doc = "      ],"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"Item\": {"]
#[doc = "      \"title\": \"Item\","]
#[doc = "      \"description\": \"Module name - lowercase\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"hpt_flakmortar_turret_medium\","]
#[doc = "        \"hpt_guardian_gausscannon_fixed_medium\","]
#[doc = "        \"hpt_heatsinklauncher_turret_tiny\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"On\": {"]
#[doc = "      \"title\": \"On\","]
#[doc = "      \"examples\": ["]
#[doc = "        true,"]
#[doc = "        false"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"Priority\": {"]
#[doc = "      \"title\": \"Priority\","]
#[doc = "      \"examples\": ["]
#[doc = "        0,"]
#[doc = "        1,"]
#[doc = "        4"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Slot\": {"]
#[doc = "      \"title\": \"Slot\","]
#[doc = "      \"description\": \"Slot name\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"LargeHardpoint1\","]
#[doc = "        \"LargeHardpoint2\","]
#[doc = "        \"LargeHardpoint3\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Value\": {"]
#[doc = "      \"title\": \"Value\","]
#[doc = "      \"examples\": ["]
#[doc = "        1104948,"]
#[doc = "        3072,"]
#[doc = "        356556"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ModulesItem {
    #[doc = "If relevant. For a passenger cabin, AmmoInClip holds the number of places in the cabin."]
    #[serde(
        rename = "AmmoInClip",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub ammo_in_clip: ::std::option::Option<i64>,
    #[doc = "if relevant"]
    #[serde(
        rename = "AmmoInHopper",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub ammo_in_hopper: ::std::option::Option<i64>,
    #[serde(
        rename = "Engineering",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub engineering: ::std::option::Option<Engineering>,
    #[serde(rename = "Health")]
    pub health: f64,
    #[doc = "Module name - lowercase"]
    #[serde(rename = "Item")]
    pub item: ::std::string::String,
    #[serde(rename = "On")]
    pub on: bool,
    #[serde(rename = "Priority")]
    pub priority: i64,
    #[doc = "Slot name"]
    #[serde(rename = "Slot")]
    pub slot: ::std::string::String,
    #[serde(
        rename = "Value",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub value: ::std::option::Option<i64>,
}
impl ::std::convert::From<&ModulesItem> for ModulesItem {
    fn from(value: &ModulesItem) -> Self {
        value.clone()
    }
}

impl Loadout {
    pub fn event_value() -> ::std::string::String {
        "Loadout".to_string()
    }
}
