#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "`ItemsItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"BuyPrice\","]
#[doc = "    \"Category\","]
#[doc = "    \"Consumer\","]
#[doc = "    \"Demand\","]
#[doc = "    \"DemandBracket\","]
#[doc = "    \"MeanPrice\","]
#[doc = "    \"Name\","]
#[doc = "    \"Producer\","]
#[doc = "    \"Rare\","]
#[doc = "    \"SellPrice\","]
#[doc = "    \"Stock\","]
#[doc = "    \"StockBracket\","]
#[doc = "    \"id\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"BuyPrice\": {"]
#[doc = "      \"title\": \"BuyPrice\","]
#[doc = "      \"examples\": ["]
#[doc = "        0"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Category\": {"]
#[doc = "      \"title\": \"Category\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"$MARKET_category_metals;\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Category_Localised\": {"]
#[doc = "      \"title\": \"Category_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Metals\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Consumer\": {"]
#[doc = "      \"title\": \"Consumer\","]
#[doc = "      \"examples\": ["]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"Demand\": {"]
#[doc = "      \"title\": \"Demand\","]
#[doc = "      \"examples\": ["]
#[doc = "        9182,"]
#[doc = "        123183,"]
#[doc = "        151492"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"DemandBracket\": {"]
#[doc = "      \"title\": \"DemandBracket\","]
#[doc = "      \"examples\": ["]
#[doc = "        3"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"MeanPrice\": {"]
#[doc = "      \"title\": \"MeanPrice\","]
#[doc = "      \"examples\": ["]
#[doc = "        19756,"]
#[doc = "        13244,"]
#[doc = "        9373"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Name\": {"]
#[doc = "      \"title\": \"Name\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"$platinum_name;\","]
#[doc = "        \"$palladium_name;\","]
#[doc = "        \"$gold_name;\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Name_Localised\": {"]
#[doc = "      \"title\": \"Name_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Platinum\","]
#[doc = "        \"Palladium\","]
#[doc = "        \"Gold\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Producer\": {"]
#[doc = "      \"title\": \"Producer\","]
#[doc = "      \"examples\": ["]
#[doc = "        false"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"Rare\": {"]
#[doc = "      \"title\": \"Rare\","]
#[doc = "      \"examples\": ["]
#[doc = "        false"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"SellPrice\": {"]
#[doc = "      \"title\": \"SellPrice\","]
#[doc = "      \"examples\": ["]
#[doc = "        42220,"]
#[doc = "        13999,"]
#[doc = "        10831"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Stock\": {"]
#[doc = "      \"title\": \"Stock\","]
#[doc = "      \"examples\": ["]
#[doc = "        0"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"StockBracket\": {"]
#[doc = "      \"title\": \"StockBracket\","]
#[doc = "      \"examples\": ["]
#[doc = "        0"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"id\": {"]
#[doc = "      \"title\": \"id\","]
#[doc = "      \"examples\": ["]
#[doc = "        128049152,"]
#[doc = "        128049153,"]
#[doc = "        128049154"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ItemsItem {
    #[serde(rename = "BuyPrice")]
    pub buy_price: i64,
    #[serde(rename = "Category")]
    pub category: ::std::string::String,
    #[serde(
        rename = "Category_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub category_localised: ::std::option::Option<::std::string::String>,
    #[serde(rename = "Consumer")]
    pub consumer: bool,
    #[serde(rename = "Demand")]
    pub demand: i64,
    #[serde(rename = "DemandBracket")]
    pub demand_bracket: i64,
    pub id: i64,
    #[serde(rename = "MeanPrice")]
    pub mean_price: i64,
    #[serde(rename = "Name")]
    pub name: ::std::string::String,
    #[serde(
        rename = "Name_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub name_localised: ::std::option::Option<::std::string::String>,
    #[serde(rename = "Producer")]
    pub producer: bool,
    #[serde(rename = "Rare")]
    pub rare: bool,
    #[serde(rename = "SellPrice")]
    pub sell_price: i64,
    #[serde(rename = "Stock")]
    pub stock: i64,
    #[serde(rename = "StockBracket")]
    pub stock_bracket: i64,
}
impl ::std::convert::From<&ItemsItem> for ItemsItem {
    fn from(value: &ItemsItem) -> Self {
        value.clone()
    }
}
#[doc = "When written: when accessing the commodity market in a station. A separate file Market.json is written to the same folder as the journal, containing full market price info."]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"description\": \"When written: when accessing the commodity market in a station. A separate file Market.json is written to the same folder as the journal, containing full market price info.\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"MarketID\","]
#[doc = "    \"StarSystem\","]
#[doc = "    \"StationName\","]
#[doc = "    \"StationType\","]
#[doc = "    \"event\","]
#[doc = "    \"timestamp\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"CarrierDockingAccess\": {"]
#[doc = "      \"title\": \"CarrierDockingAccess\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"all\","]
#[doc = "        \"friends\","]
#[doc = "        \"squadronfriends\","]
#[doc = "        \"squadron\","]
#[doc = "        \"none\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Items\": {"]
#[doc = "      \"title\": \"Items\","]
#[doc = "      \"description\": \"When written to Market.json\","]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"BuyPrice\","]
#[doc = "          \"Category\","]
#[doc = "          \"Consumer\","]
#[doc = "          \"Demand\","]
#[doc = "          \"DemandBracket\","]
#[doc = "          \"MeanPrice\","]
#[doc = "          \"Name\","]
#[doc = "          \"Producer\","]
#[doc = "          \"Rare\","]
#[doc = "          \"SellPrice\","]
#[doc = "          \"Stock\","]
#[doc = "          \"StockBracket\","]
#[doc = "          \"id\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"BuyPrice\": {"]
#[doc = "            \"title\": \"BuyPrice\","]
#[doc = "            \"examples\": ["]
#[doc = "              0"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"Category\": {"]
#[doc = "            \"title\": \"Category\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"$MARKET_category_metals;\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Category_Localised\": {"]
#[doc = "            \"title\": \"Category_Localised\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Metals\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Consumer\": {"]
#[doc = "            \"title\": \"Consumer\","]
#[doc = "            \"examples\": ["]
#[doc = "              true"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          },"]
#[doc = "          \"Demand\": {"]
#[doc = "            \"title\": \"Demand\","]
#[doc = "            \"examples\": ["]
#[doc = "              9182,"]
#[doc = "              123183,"]
#[doc = "              151492"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"DemandBracket\": {"]
#[doc = "            \"title\": \"DemandBracket\","]
#[doc = "            \"examples\": ["]
#[doc = "              3"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"MeanPrice\": {"]
#[doc = "            \"title\": \"MeanPrice\","]
#[doc = "            \"examples\": ["]
#[doc = "              19756,"]
#[doc = "              13244,"]
#[doc = "              9373"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"Name\": {"]
#[doc = "            \"title\": \"Name\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"$platinum_name;\","]
#[doc = "              \"$palladium_name;\","]
#[doc = "              \"$gold_name;\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Name_Localised\": {"]
#[doc = "            \"title\": \"Name_Localised\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Platinum\","]
#[doc = "              \"Palladium\","]
#[doc = "              \"Gold\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Producer\": {"]
#[doc = "            \"title\": \"Producer\","]
#[doc = "            \"examples\": ["]
#[doc = "              false"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          },"]
#[doc = "          \"Rare\": {"]
#[doc = "            \"title\": \"Rare\","]
#[doc = "            \"examples\": ["]
#[doc = "              false"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          },"]
#[doc = "          \"SellPrice\": {"]
#[doc = "            \"title\": \"SellPrice\","]
#[doc = "            \"examples\": ["]
#[doc = "              42220,"]
#[doc = "              13999,"]
#[doc = "              10831"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"Stock\": {"]
#[doc = "            \"title\": \"Stock\","]
#[doc = "            \"examples\": ["]
#[doc = "              0"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"StockBracket\": {"]
#[doc = "            \"title\": \"StockBracket\","]
#[doc = "            \"examples\": ["]
#[doc = "              0"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"id\": {"]
#[doc = "            \"title\": \"id\","]
#[doc = "            \"examples\": ["]
#[doc = "              128049152,"]
#[doc = "              128049153,"]
#[doc = "              128049154"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"MarketID\": {"]
#[doc = "      \"title\": \"MarketID\","]
#[doc = "      \"examples\": ["]
#[doc = "        3705689344,"]
#[doc = "        3226155264,"]
#[doc = "        128750927"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"StarSystem\": {"]
#[doc = "      \"title\": \"StarSystem\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"HIP 20485\","]
#[doc = "        \"Thereila\","]
#[doc = "        \"Pleione\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"StationName\": {"]
#[doc = "      \"title\": \"StationName\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"A1A-B2B\","]
#[doc = "        \"Gann Dock\","]
#[doc = "        \"$EXT_PANEL_ColonisationShip:#index=1;\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"StationName_Localised\": {"]
#[doc = "      \"title\": \"StationName_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"System Colonisation Ship\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"StationType\": {"]
#[doc = "      \"title\": \"StationType\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"FleetCarrier\","]
#[doc = "        \"Orbis\","]
#[doc = "        \"AsteroidBase\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"event\": {"]
#[doc = "      \"title\": \"event\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"AfmuRepairs\","]
#[doc = "        \"FSDJump\","]
#[doc = "        \"Location\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"timestamp\": {"]
#[doc = "      \"title\": \"timestamp\","]
#[doc = "      \"description\": \"Timestamp in UTC, ISO 8601\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"2022-09-11T22:00:45Z\","]
#[doc = "        \"2022-09-12T08:54:21Z\","]
#[doc = "        \"2022-09-12T08:54:24Z\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"format\": \"date-time\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct Market {
    #[serde(
        rename = "CarrierDockingAccess",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub carrier_docking_access: ::std::option::Option<::std::string::String>,
    #[serde(skip_deserializing, default = "Market::event_value")]
    pub event: String,
    #[doc = "When written to Market.json"]
    #[serde(
        rename = "Items",
        default,
        skip_serializing_if = "::std::vec::Vec::is_empty"
    )]
    pub items: ::std::vec::Vec<ItemsItem>,
    #[serde(rename = "MarketID")]
    pub market_id: i64,
    #[serde(rename = "StarSystem")]
    pub star_system: ::std::string::String,
    #[serde(rename = "StationName")]
    pub station_name: ::std::string::String,
    #[serde(
        rename = "StationName_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub station_name_localised: ::std::option::Option<::std::string::String>,
    #[serde(rename = "StationType")]
    pub station_type: ::std::string::String,
    #[doc = "Timestamp in UTC, ISO 8601"]
    pub timestamp: ::chrono::DateTime<::chrono::offset::Utc>,
}
impl ::std::convert::From<&Market> for Market {
    fn from(value: &Market) -> Self {
        value.clone()
    }
}

impl Market {
    pub fn event_value() -> ::std::string::String {
        "Market".to_string()
    }
}
