#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "`ActiveItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Expires\","]
#[doc = "    \"MissionID\","]
#[doc = "    \"Name\","]
#[doc = "    \"PassengerMission\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Expires\": {"]
#[doc = "      \"title\": \"Expires\","]
#[doc = "      \"description\": \"Time left in seconds\","]
#[doc = "      \"examples\": ["]
#[doc = "        23337,"]
#[doc = "        24071,"]
#[doc = "        23981"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"MissionID\": {"]
#[doc = "      \"title\": \"MissionID\","]
#[doc = "      \"examples\": ["]
#[doc = "        868354915,"]
#[doc = "        868354949,"]
#[doc = "        868354970"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Name\": {"]
#[doc = "      \"title\": \"Name\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Mission_OnFoot_Hack_Download_Covert_MB_name\","]
#[doc = "        \"Mission_OnFoot_Hack_Download_MB_name\","]
#[doc = "        \"Mission_OnFoot_Sabotage_Power_MB_name\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Name_Localised\": {"]
#[doc = "      \"title\": \"Name_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Construction du port principal\","]
#[doc = "        \"Construct primary port\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"PassengerMission\": {"]
#[doc = "      \"title\": \"PassengerMission\","]
#[doc = "      \"examples\": ["]
#[doc = "        false,"]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ActiveItem {
    #[doc = "Time left in seconds"]
    #[serde(rename = "Expires")]
    pub expires: i64,
    #[serde(rename = "MissionID")]
    pub mission_id: i64,
    #[serde(rename = "Name")]
    pub name: ::std::string::String,
    #[serde(
        rename = "Name_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub name_localised: ::std::option::Option<::std::string::String>,
    #[serde(rename = "PassengerMission")]
    pub passenger_mission: bool,
}
impl ::std::convert::From<&ActiveItem> for ActiveItem {
    fn from(value: &ActiveItem) -> Self {
        value.clone()
    }
}
#[doc = "`CompleteItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Expires\","]
#[doc = "    \"MissionID\","]
#[doc = "    \"Name\","]
#[doc = "    \"PassengerMission\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Expires\": {"]
#[doc = "      \"title\": \"Expires\","]
#[doc = "      \"description\": \"Time left in seconds\","]
#[doc = "      \"examples\": ["]
#[doc = "        23337,"]
#[doc = "        24071,"]
#[doc = "        23981"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"MissionID\": {"]
#[doc = "      \"title\": \"MissionID\","]
#[doc = "      \"examples\": ["]
#[doc = "        868354915,"]
#[doc = "        868354949,"]
#[doc = "        868354970"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Name\": {"]
#[doc = "      \"title\": \"Name\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Mission_OnFoot_Hack_Download_Covert_MB_name\","]
#[doc = "        \"Mission_OnFoot_Hack_Download_MB_name\","]
#[doc = "        \"Mission_OnFoot_Sabotage_Power_MB_name\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Name_Localised\": {"]
#[doc = "      \"title\": \"Name_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Construction du port principal\","]
#[doc = "        \"Construct primary port\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"PassengerMission\": {"]
#[doc = "      \"title\": \"PassengerMission\","]
#[doc = "      \"examples\": ["]
#[doc = "        false,"]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CompleteItem {
    #[doc = "Time left in seconds"]
    #[serde(rename = "Expires")]
    pub expires: i64,
    #[serde(rename = "MissionID")]
    pub mission_id: i64,
    #[serde(rename = "Name")]
    pub name: ::std::string::String,
    #[serde(
        rename = "Name_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub name_localised: ::std::option::Option<::std::string::String>,
    #[serde(rename = "PassengerMission")]
    pub passenger_mission: bool,
}
impl ::std::convert::From<&CompleteItem> for CompleteItem {
    fn from(value: &CompleteItem) -> Self {
        value.clone()
    }
}
#[doc = "`FailedItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Expires\","]
#[doc = "    \"MissionID\","]
#[doc = "    \"Name\","]
#[doc = "    \"PassengerMission\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Expires\": {"]
#[doc = "      \"title\": \"Expires\","]
#[doc = "      \"description\": \"Time left in seconds\","]
#[doc = "      \"examples\": ["]
#[doc = "        0"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"MissionID\": {"]
#[doc = "      \"title\": \"MissionID\","]
#[doc = "      \"examples\": ["]
#[doc = "        868354915,"]
#[doc = "        868354949,"]
#[doc = "        868354970"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Name\": {"]
#[doc = "      \"title\": \"Name\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Mission_OnFoot_Hack_Download_Covert_MB_name\","]
#[doc = "        \"Mission_OnFoot_Hack_Download_MB_name\","]
#[doc = "        \"Mission_OnFoot_Sabotage_Power_MB_name\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Name_Localised\": {"]
#[doc = "      \"title\": \"Name_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Construction du port principal\","]
#[doc = "        \"Construct primary port\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"PassengerMission\": {"]
#[doc = "      \"title\": \"PassengerMission\","]
#[doc = "      \"examples\": ["]
#[doc = "        false,"]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct FailedItem {
    #[doc = "Time left in seconds"]
    #[serde(rename = "Expires")]
    pub expires: i64,
    #[serde(rename = "MissionID")]
    pub mission_id: i64,
    #[serde(rename = "Name")]
    pub name: ::std::string::String,
    #[serde(
        rename = "Name_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub name_localised: ::std::option::Option<::std::string::String>,
    #[serde(rename = "PassengerMission")]
    pub passenger_mission: bool,
}
impl ::std::convert::From<&FailedItem> for FailedItem {
    fn from(value: &FailedItem) -> Self {
        value.clone()
    }
}
#[doc = "When written: at startup"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"description\": \"When written: at startup\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Active\","]
#[doc = "    \"Complete\","]
#[doc = "    \"Failed\","]
#[doc = "    \"event\","]
#[doc = "    \"timestamp\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Active\": {"]
#[doc = "      \"title\": \"Active\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"Expires\","]
#[doc = "          \"MissionID\","]
#[doc = "          \"Name\","]
#[doc = "          \"PassengerMission\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"Expires\": {"]
#[doc = "            \"title\": \"Expires\","]
#[doc = "            \"description\": \"Time left in seconds\","]
#[doc = "            \"examples\": ["]
#[doc = "              23337,"]
#[doc = "              24071,"]
#[doc = "              23981"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"MissionID\": {"]
#[doc = "            \"title\": \"MissionID\","]
#[doc = "            \"examples\": ["]
#[doc = "              868354915,"]
#[doc = "              868354949,"]
#[doc = "              868354970"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"Name\": {"]
#[doc = "            \"title\": \"Name\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Mission_OnFoot_Hack_Download_Covert_MB_name\","]
#[doc = "              \"Mission_OnFoot_Hack_Download_MB_name\","]
#[doc = "              \"Mission_OnFoot_Sabotage_Power_MB_name\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Name_Localised\": {"]
#[doc = "            \"title\": \"Name_Localised\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Construction du port principal\","]
#[doc = "              \"Construct primary port\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"PassengerMission\": {"]
#[doc = "            \"title\": \"PassengerMission\","]
#[doc = "            \"examples\": ["]
#[doc = "              false,"]
#[doc = "              true"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"Complete\": {"]
#[doc = "      \"title\": \"Complete\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"Expires\","]
#[doc = "          \"MissionID\","]
#[doc = "          \"Name\","]
#[doc = "          \"PassengerMission\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"Expires\": {"]
#[doc = "            \"title\": \"Expires\","]
#[doc = "            \"description\": \"Time left in seconds\","]
#[doc = "            \"examples\": ["]
#[doc = "              23337,"]
#[doc = "              24071,"]
#[doc = "              23981"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"MissionID\": {"]
#[doc = "            \"title\": \"MissionID\","]
#[doc = "            \"examples\": ["]
#[doc = "              868354915,"]
#[doc = "              868354949,"]
#[doc = "              868354970"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"Name\": {"]
#[doc = "            \"title\": \"Name\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Mission_OnFoot_Hack_Download_Covert_MB_name\","]
#[doc = "              \"Mission_OnFoot_Hack_Download_MB_name\","]
#[doc = "              \"Mission_OnFoot_Sabotage_Power_MB_name\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Name_Localised\": {"]
#[doc = "            \"title\": \"Name_Localised\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Construction du port principal\","]
#[doc = "              \"Construct primary port\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"PassengerMission\": {"]
#[doc = "            \"title\": \"PassengerMission\","]
#[doc = "            \"examples\": ["]
#[doc = "              false,"]
#[doc = "              true"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"Failed\": {"]
#[doc = "      \"title\": \"Failed\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"Expires\","]
#[doc = "          \"MissionID\","]
#[doc = "          \"Name\","]
#[doc = "          \"PassengerMission\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"Expires\": {"]
#[doc = "            \"title\": \"Expires\","]
#[doc = "            \"description\": \"Time left in seconds\","]
#[doc = "            \"examples\": ["]
#[doc = "              0"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"MissionID\": {"]
#[doc = "            \"title\": \"MissionID\","]
#[doc = "            \"examples\": ["]
#[doc = "              868354915,"]
#[doc = "              868354949,"]
#[doc = "              868354970"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"Name\": {"]
#[doc = "            \"title\": \"Name\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Mission_OnFoot_Hack_Download_Covert_MB_name\","]
#[doc = "              \"Mission_OnFoot_Hack_Download_MB_name\","]
#[doc = "              \"Mission_OnFoot_Sabotage_Power_MB_name\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Name_Localised\": {"]
#[doc = "            \"title\": \"Name_Localised\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Construction du port principal\","]
#[doc = "              \"Construct primary port\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"PassengerMission\": {"]
#[doc = "            \"title\": \"PassengerMission\","]
#[doc = "            \"examples\": ["]
#[doc = "              false,"]
#[doc = "              true"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"event\": {"]
#[doc = "      \"title\": \"event\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"AfmuRepairs\","]
#[doc = "        \"FSDJump\","]
#[doc = "        \"Location\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"timestamp\": {"]
#[doc = "      \"title\": \"timestamp\","]
#[doc = "      \"description\": \"Timestamp in UTC, ISO 8601\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"2022-09-11T22:00:45Z\","]
#[doc = "        \"2022-09-12T08:54:21Z\","]
#[doc = "        \"2022-09-12T08:54:24Z\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"format\": \"date-time\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct Missions {
    #[serde(rename = "Active")]
    pub active: ::std::vec::Vec<ActiveItem>,
    #[serde(rename = "Complete")]
    pub complete: ::std::vec::Vec<CompleteItem>,
    #[serde(skip_deserializing, default = "Missions::event_value")]
    pub event: String,
    #[serde(rename = "Failed")]
    pub failed: ::std::vec::Vec<FailedItem>,
    #[doc = "Timestamp in UTC, ISO 8601"]
    pub timestamp: ::chrono::DateTime<::chrono::offset::Utc>,
}
impl ::std::convert::From<&Missions> for Missions {
    fn from(value: &Missions) -> Self {
        value.clone()
    }
}

impl Missions {
    pub fn event_value() -> ::std::string::String {
        "Missions".to_string()
    }
}
