#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "definitions for backpack and shiplocker events"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"description\": \"definitions for backpack and shiplocker events\","]
#[doc = "  \"required\": ["]
#[doc = "    \"event\","]
#[doc = "    \"timestamp\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"event\": {"]
#[doc = "      \"title\": \"event\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"AfmuRepairs\","]
#[doc = "        \"FSDJump\","]
#[doc = "        \"Location\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"timestamp\": {"]
#[doc = "      \"title\": \"timestamp\","]
#[doc = "      \"description\": \"Timestamp in UTC, ISO 8601\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"2022-09-11T22:00:45Z\","]
#[doc = "        \"2022-09-12T08:54:21Z\","]
#[doc = "        \"2022-09-12T08:54:24Z\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"format\": \"date-time\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"definitions\": {"]
#[doc = "    \"Component\": {"]
#[doc = "      \"additionalProperties\": false,"]
#[doc = "      \"properties\": {"]
#[doc = "        \"Count\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            114,"]
#[doc = "            2,"]
#[doc = "            4"]
#[doc = "          ],"]
#[doc = "          \"title\": \"Count\","]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"MissionID\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            836665448,"]
#[doc = "            836922172,"]
#[doc = "            836961350"]
#[doc = "          ],"]
#[doc = "          \"title\": \"MissionID\","]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"Name\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            \"graphene\","]
#[doc = "            \"aerogel\","]
#[doc = "            \"chemicalcatalyst\""]
#[doc = "          ],"]
#[doc = "          \"title\": \"Name\","]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"Name_Localised\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            \"Chemical Catalyst\","]
#[doc = "            \"Chemical Superbase\","]
#[doc = "            \"Circuit Board\""]
#[doc = "          ],"]
#[doc = "          \"title\": \"Name_Localised\","]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"OwnerID\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            0"]
#[doc = "          ],"]
#[doc = "          \"title\": \"OwnerID\","]
#[doc = "          \"type\": \"integer\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"required\": ["]
#[doc = "        \"Name\","]
#[doc = "        \"OwnerID\","]
#[doc = "        \"Count\""]
#[doc = "      ],"]
#[doc = "      \"title\": \"Component\","]
#[doc = "      \"type\": \"object\""]
#[doc = "    },"]
#[doc = "    \"Consumable\": {"]
#[doc = "      \"additionalProperties\": false,"]
#[doc = "      \"properties\": {"]
#[doc = "        \"Count\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            100,"]
#[doc = "            99,"]
#[doc = "            97"]
#[doc = "          ],"]
#[doc = "          \"title\": \"Count\","]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"Name\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            \"healthpack\","]
#[doc = "            \"energycell\","]
#[doc = "            \"amm_grenade_emp\""]
#[doc = "          ],"]
#[doc = "          \"title\": \"Name\","]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"Name_Localised\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            \"Medkit\","]
#[doc = "            \"Energy Cell\","]
#[doc = "            \"Shield Disruptor\""]
#[doc = "          ],"]
#[doc = "          \"title\": \"Name_Localised\","]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"OwnerID\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            0"]
#[doc = "          ],"]
#[doc = "          \"title\": \"OwnerID\","]
#[doc = "          \"type\": \"integer\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"required\": ["]
#[doc = "        \"Name\","]
#[doc = "        \"OwnerID\","]
#[doc = "        \"Count\""]
#[doc = "      ],"]
#[doc = "      \"title\": \"Consumable\","]
#[doc = "      \"type\": \"object\""]
#[doc = "    },"]
#[doc = "    \"Data\": {"]
#[doc = "      \"additionalProperties\": false,"]
#[doc = "      \"properties\": {"]
#[doc = "        \"Count\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            1,"]
#[doc = "            3,"]
#[doc = "            4"]
#[doc = "          ],"]
#[doc = "          \"title\": \"Count\","]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"MissionID\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            779372801,"]
#[doc = "            780055610,"]
#[doc = "            783435673"]
#[doc = "          ],"]
#[doc = "          \"title\": \"MissionID\","]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"Name\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            \"virus\","]
#[doc = "            \"slushfundlogs\","]
#[doc = "            \"employeegeneticdata\""]
#[doc = "          ],"]
#[doc = "          \"title\": \"Name\","]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"Name_Localised\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            \"Slush Fund Logs\","]
#[doc = "            \"Employee Genetic Data\","]
#[doc = "            \"Medical Records\""]
#[doc = "          ],"]
#[doc = "          \"title\": \"Name_Localised\","]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"OwnerID\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            5352618,"]
#[doc = "            0,"]
#[doc = "            175185"]
#[doc = "          ],"]
#[doc = "          \"title\": \"OwnerID\","]
#[doc = "          \"type\": \"integer\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"required\": ["]
#[doc = "        \"Name\","]
#[doc = "        \"OwnerID\","]
#[doc = "        \"Count\""]
#[doc = "      ],"]
#[doc = "      \"title\": \"Data\","]
#[doc = "      \"type\": \"object\""]
#[doc = "    },"]
#[doc = "    \"Item\": {"]
#[doc = "      \"additionalProperties\": false,"]
#[doc = "      \"properties\": {"]
#[doc = "        \"Count\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            1,"]
#[doc = "            41,"]
#[doc = "            8"]
#[doc = "          ],"]
#[doc = "          \"title\": \"Count\","]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"MissionID\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            779192772,"]
#[doc = "            784083658,"]
#[doc = "            784158082"]
#[doc = "          ],"]
#[doc = "          \"title\": \"MissionID\","]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        \"Name\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            \"refinementprocesssample\","]
#[doc = "            \"chemicalsample\","]
#[doc = "            \"mutageniccatalyst\""]
#[doc = "          ],"]
#[doc = "          \"title\": \"Name\","]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"Name_Localised\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            \"Refinement Process Sample\","]
#[doc = "            \"Chemical Sample\","]
#[doc = "            \"Mutagenic Catalyst\""]
#[doc = "          ],"]
#[doc = "          \"title\": \"Name_Localised\","]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        \"OwnerID\": {"]
#[doc = "          \"examples\": ["]
#[doc = "            0,"]
#[doc = "            2953036023,"]
#[doc = "            5352618"]
#[doc = "          ],"]
#[doc = "          \"title\": \"OwnerID\","]
#[doc = "          \"type\": \"integer\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"required\": ["]
#[doc = "        \"Name\","]
#[doc = "        \"OwnerID\","]
#[doc = "        \"Count\""]
#[doc = "      ],"]
#[doc = "      \"title\": \"Item\","]
#[doc = "      \"type\": \"object\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct ShipLockerBackpack {
    #[serde(skip_deserializing, default = "ShipLockerBackpack::event_value")]
    pub event: String,
    #[doc = "Timestamp in UTC, ISO 8601"]
    pub timestamp: ::chrono::DateTime<::chrono::offset::Utc>,
}
impl ::std::convert::From<&ShipLockerBackpack> for ShipLockerBackpack {
    fn from(value: &ShipLockerBackpack) -> Self {
        value.clone()
    }
}

impl ShipLockerBackpack {
    pub fn event_value() -> ::std::string::String {
        "ShipLockerBackpack".to_string()
    }
}
