#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "`ShipsHereItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Hot\","]
#[doc = "    \"ShipID\","]
#[doc = "    \"ShipType\","]
#[doc = "    \"Value\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Hot\": {"]
#[doc = "      \"title\": \"Hot\","]
#[doc = "      \"examples\": ["]
#[doc = "        false,"]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"Name\": {"]
#[doc = "      \"title\": \"Name\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"SHIFTY\","]
#[doc = "        \"JOBHOPPER\","]
#[doc = "        \"STARHOPPER\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"ShipID\": {"]
#[doc = "      \"title\": \"ShipID\","]
#[doc = "      \"examples\": ["]
#[doc = "        32,"]
#[doc = "        31,"]
#[doc = "        0"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"ShipType\": {"]
#[doc = "      \"title\": \"ShipType\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"vulture\","]
#[doc = "        \"empire_courier\","]
#[doc = "        \"sidewinder\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"ShipType_Localised\": {"]
#[doc = "      \"title\": \"ShipType_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Imperial Courier\","]
#[doc = "        \"Viper Mk III\","]
#[doc = "        \"Type-6 Transporter\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"Value\": {"]
#[doc = "      \"title\": \"Value\","]
#[doc = "      \"examples\": ["]
#[doc = "        0,"]
#[doc = "        46998,"]
#[doc = "        210072"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ShipsHereItem {
    #[serde(rename = "Hot")]
    pub hot: bool,
    #[serde(
        rename = "Name",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub name: ::std::option::Option<::std::string::String>,
    #[serde(rename = "ShipID")]
    pub ship_id: i64,
    #[serde(rename = "ShipType")]
    pub ship_type: ::std::string::String,
    #[serde(
        rename = "ShipType_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub ship_type_localised: ::std::option::Option<::std::string::String>,
    #[serde(rename = "Value")]
    pub value: i64,
}
impl ::std::convert::From<&ShipsHereItem> for ShipsHereItem {
    fn from(value: &ShipsHereItem) -> Self {
        value.clone()
    }
}
#[doc = "`ShipsRemoteItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"Hot\","]
#[doc = "    \"ShipID\","]
#[doc = "    \"ShipType\","]
#[doc = "    \"Value\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"Hot\": {"]
#[doc = "      \"title\": \"Hot\","]
#[doc = "      \"examples\": ["]
#[doc = "        false,"]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"InTransit\": {"]
#[doc = "      \"title\": \"InTransit\","]
#[doc = "      \"description\": \"If the ship is in transit\","]
#[doc = "      \"examples\": ["]
#[doc = "        true"]
#[doc = "      ],"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"Name\": {"]
#[doc = "      \"title\": \"Name\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"SHIFTY\","]
#[doc = "        \"\","]
#[doc = "        \"PREDATOR\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"ShipID\": {"]
#[doc = "      \"title\": \"ShipID\","]
#[doc = "      \"examples\": ["]
#[doc = "        0,"]
#[doc = "        2,"]
#[doc = "        3"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"ShipMarketID\": {"]
#[doc = "      \"title\": \"ShipMarketID\","]
#[doc = "      \"description\": \"If the ship is not in transit\","]
#[doc = "      \"examples\": ["]
#[doc = "        3705689344,"]
#[doc = "        128666762,"]
#[doc = "        3703568640"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"ShipType\": {"]
#[doc = "      \"title\": \"ShipType\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"SideWinder\","]
#[doc = "        \"Hauler\","]
#[doc = "        \"Viper\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"ShipType_Localised\": {"]
#[doc = "      \"title\": \"ShipType_Localised\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Viper Mk III\","]
#[doc = "        \"Type-6 Transporter\","]
#[doc = "        \"Type-9 Heavy\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"StarSystem\": {"]
#[doc = "      \"title\": \"StarSystem\","]
#[doc = "      \"description\": \"If the ship is not in transit\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Nuenets\","]
#[doc = "        \"LFT 926\","]
#[doc = "        \"Shinrarta Dezhra\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"TransferPrice\": {"]
#[doc = "      \"title\": \"TransferPrice\","]
#[doc = "      \"description\": \"If the ship is not in transit\","]
#[doc = "      \"examples\": ["]
#[doc = "        24311,"]
#[doc = "        39042,"]
#[doc = "        171040"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"TransferTime\": {"]
#[doc = "      \"title\": \"TransferTime\","]
#[doc = "      \"description\": \"If the ship is not in transit\","]
#[doc = "      \"examples\": ["]
#[doc = "        121682,"]
#[doc = "        356,"]
#[doc = "        4719"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"Value\": {"]
#[doc = "      \"title\": \"Value\","]
#[doc = "      \"examples\": ["]
#[doc = "        0,"]
#[doc = "        46998,"]
#[doc = "        210072"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ShipsRemoteItem {
    #[serde(rename = "Hot")]
    pub hot: bool,
    #[doc = "If the ship is in transit"]
    #[serde(
        rename = "InTransit",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub in_transit: ::std::option::Option<bool>,
    #[serde(
        rename = "Name",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub name: ::std::option::Option<::std::string::String>,
    #[serde(rename = "ShipID")]
    pub ship_id: i64,
    #[doc = "If the ship is not in transit"]
    #[serde(
        rename = "ShipMarketID",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub ship_market_id: ::std::option::Option<i64>,
    #[serde(rename = "ShipType")]
    pub ship_type: ::std::string::String,
    #[serde(
        rename = "ShipType_Localised",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub ship_type_localised: ::std::option::Option<::std::string::String>,
    #[doc = "If the ship is not in transit"]
    #[serde(
        rename = "StarSystem",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub star_system: ::std::option::Option<::std::string::String>,
    #[doc = "If the ship is not in transit"]
    #[serde(
        rename = "TransferPrice",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub transfer_price: ::std::option::Option<i64>,
    #[doc = "If the ship is not in transit"]
    #[serde(
        rename = "TransferTime",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub transfer_time: ::std::option::Option<i64>,
    #[serde(rename = "Value")]
    pub value: i64,
}
impl ::std::convert::From<&ShipsRemoteItem> for ShipsRemoteItem {
    fn from(value: &ShipsRemoteItem) -> Self {
        value.clone()
    }
}
#[doc = "When written: when visiting shipyard"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"description\": \"When written: when visiting shipyard\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"MarketID\","]
#[doc = "    \"ShipsHere\","]
#[doc = "    \"ShipsRemote\","]
#[doc = "    \"StarSystem\","]
#[doc = "    \"StationName\","]
#[doc = "    \"event\","]
#[doc = "    \"timestamp\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"MarketID\": {"]
#[doc = "      \"title\": \"MarketID\","]
#[doc = "      \"examples\": ["]
#[doc = "        3705689344,"]
#[doc = "        3700367104,"]
#[doc = "        128666762"]
#[doc = "      ],"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"ShipsHere\": {"]
#[doc = "      \"title\": \"ShipsHere\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"Hot\","]
#[doc = "          \"ShipID\","]
#[doc = "          \"ShipType\","]
#[doc = "          \"Value\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"Hot\": {"]
#[doc = "            \"title\": \"Hot\","]
#[doc = "            \"examples\": ["]
#[doc = "              false,"]
#[doc = "              true"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          },"]
#[doc = "          \"Name\": {"]
#[doc = "            \"title\": \"Name\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"SHIFTY\","]
#[doc = "              \"JOBHOPPER\","]
#[doc = "              \"STARHOPPER\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"ShipID\": {"]
#[doc = "            \"title\": \"ShipID\","]
#[doc = "            \"examples\": ["]
#[doc = "              32,"]
#[doc = "              31,"]
#[doc = "              0"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"ShipType\": {"]
#[doc = "            \"title\": \"ShipType\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"vulture\","]
#[doc = "              \"empire_courier\","]
#[doc = "              \"sidewinder\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"ShipType_Localised\": {"]
#[doc = "            \"title\": \"ShipType_Localised\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Imperial Courier\","]
#[doc = "              \"Viper Mk III\","]
#[doc = "              \"Type-6 Transporter\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"Value\": {"]
#[doc = "            \"title\": \"Value\","]
#[doc = "            \"examples\": ["]
#[doc = "              0,"]
#[doc = "              46998,"]
#[doc = "              210072"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"ShipsRemote\": {"]
#[doc = "      \"title\": \"ShipsRemote\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"Hot\","]
#[doc = "          \"ShipID\","]
#[doc = "          \"ShipType\","]
#[doc = "          \"Value\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"Hot\": {"]
#[doc = "            \"title\": \"Hot\","]
#[doc = "            \"examples\": ["]
#[doc = "              false,"]
#[doc = "              true"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          },"]
#[doc = "          \"InTransit\": {"]
#[doc = "            \"title\": \"InTransit\","]
#[doc = "            \"description\": \"If the ship is in transit\","]
#[doc = "            \"examples\": ["]
#[doc = "              true"]
#[doc = "            ],"]
#[doc = "            \"type\": \"boolean\""]
#[doc = "          },"]
#[doc = "          \"Name\": {"]
#[doc = "            \"title\": \"Name\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"SHIFTY\","]
#[doc = "              \"\","]
#[doc = "              \"PREDATOR\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"ShipID\": {"]
#[doc = "            \"title\": \"ShipID\","]
#[doc = "            \"examples\": ["]
#[doc = "              0,"]
#[doc = "              2,"]
#[doc = "              3"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"ShipMarketID\": {"]
#[doc = "            \"title\": \"ShipMarketID\","]
#[doc = "            \"description\": \"If the ship is not in transit\","]
#[doc = "            \"examples\": ["]
#[doc = "              3705689344,"]
#[doc = "              128666762,"]
#[doc = "              3703568640"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"ShipType\": {"]
#[doc = "            \"title\": \"ShipType\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"SideWinder\","]
#[doc = "              \"Hauler\","]
#[doc = "              \"Viper\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"ShipType_Localised\": {"]
#[doc = "            \"title\": \"ShipType_Localised\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Viper Mk III\","]
#[doc = "              \"Type-6 Transporter\","]
#[doc = "              \"Type-9 Heavy\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"StarSystem\": {"]
#[doc = "            \"title\": \"StarSystem\","]
#[doc = "            \"description\": \"If the ship is not in transit\","]
#[doc = "            \"examples\": ["]
#[doc = "              \"Nuenets\","]
#[doc = "              \"LFT 926\","]
#[doc = "              \"Shinrarta Dezhra\""]
#[doc = "            ],"]
#[doc = "            \"type\": \"string\""]
#[doc = "          },"]
#[doc = "          \"TransferPrice\": {"]
#[doc = "            \"title\": \"TransferPrice\","]
#[doc = "            \"description\": \"If the ship is not in transit\","]
#[doc = "            \"examples\": ["]
#[doc = "              24311,"]
#[doc = "              39042,"]
#[doc = "              171040"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"TransferTime\": {"]
#[doc = "            \"title\": \"TransferTime\","]
#[doc = "            \"description\": \"If the ship is not in transit\","]
#[doc = "            \"examples\": ["]
#[doc = "              121682,"]
#[doc = "              356,"]
#[doc = "              4719"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          },"]
#[doc = "          \"Value\": {"]
#[doc = "            \"title\": \"Value\","]
#[doc = "            \"examples\": ["]
#[doc = "              0,"]
#[doc = "              46998,"]
#[doc = "              210072"]
#[doc = "            ],"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        \"additionalProperties\": false"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"StarSystem\": {"]
#[doc = "      \"title\": \"StarSystem\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"Celaeno\","]
#[doc = "        \"HIP 20485\","]
#[doc = "        \"Swoiwns ZD-B d1\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"StationName\": {"]
#[doc = "      \"title\": \"StationName\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"A1A-B2B\","]
#[doc = "        \"Jameson Memorial\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"event\": {"]
#[doc = "      \"title\": \"event\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"AfmuRepairs\","]
#[doc = "        \"FSDJump\","]
#[doc = "        \"Location\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"timestamp\": {"]
#[doc = "      \"title\": \"timestamp\","]
#[doc = "      \"description\": \"Timestamp in UTC, ISO 8601\","]
#[doc = "      \"examples\": ["]
#[doc = "        \"2022-09-11T22:00:45Z\","]
#[doc = "        \"2022-09-12T08:54:21Z\","]
#[doc = "        \"2022-09-12T08:54:24Z\""]
#[doc = "      ],"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"format\": \"date-time\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct StoredShips {
    #[serde(skip_deserializing, default = "StoredShips::event_value")]
    pub event: String,
    #[serde(rename = "MarketID")]
    pub market_id: i64,
    #[serde(rename = "ShipsHere")]
    pub ships_here: ::std::vec::Vec<ShipsHereItem>,
    #[serde(rename = "ShipsRemote")]
    pub ships_remote: ::std::vec::Vec<ShipsRemoteItem>,
    #[serde(rename = "StarSystem")]
    pub star_system: ::std::string::String,
    #[serde(rename = "StationName")]
    pub station_name: ::std::string::String,
    #[doc = "Timestamp in UTC, ISO 8601"]
    pub timestamp: ::chrono::DateTime<::chrono::offset::Utc>,
}
impl ::std::convert::From<&StoredShips> for StoredShips {
    fn from(value: &StoredShips) -> Self {
        value.clone()
    }
}

impl StoredShips {
    pub fn event_value() -> ::std::string::String {
        "StoredShips".to_string()
    }
}
